import type { CatalogExpansionDeviceSeed } from "./catalog-expansion-100";
import type { CatalogModuleSeed } from "./extended-catalog-modules";

type DisplayTechnology = NonNullable<
  CatalogModuleSeed["display"]
>["technology"];
type MemoryStandard = CatalogModuleSeed["memory"]["standard"];
type StorageStandard = CatalogModuleSeed["storage"]["standard"];
type OperatingSystem = CatalogModuleSeed["operatingSystem"];
type Wireless = CatalogModuleSeed["wireless"][number];

type Platform = {
  name: string;
  slug: string;
  maker: string;
  cpuName: string;
  cpuSlug: string;
  cores: number;
  gpuName: string;
  gpuSlug: string;
};

const PLATFORMS = {
  snapdragon710: {
    name: "Qualcomm Snapdragon 710",
    slug: "qualcomm-snapdragon-710",
    maker: "qualcomm",
    cpuName: "Qualcomm Kryo 360 CPU",
    cpuSlug: "qualcomm-kryo-360",
    cores: 8,
    gpuName: "Adreno 616",
    gpuSlug: "adreno-616",
  },
  snapdragon821: {
    name: "Qualcomm Snapdragon 821",
    slug: "qualcomm-snapdragon-821",
    maker: "qualcomm",
    cpuName: "Qualcomm Kryo (Snapdragon 821)",
    cpuSlug: "qualcomm-kryo-snapdragon-821",
    cores: 4,
    gpuName: "Adreno 530",
    gpuSlug: "adreno-530",
  },
  snapdragon835: {
    name: "Qualcomm Snapdragon 835",
    slug: "qualcomm-snapdragon-835",
    maker: "qualcomm",
    cpuName: "Qualcomm Kryo 280 CPU",
    cpuSlug: "qualcomm-kryo-280",
    cores: 8,
    gpuName: "Adreno 540",
    gpuSlug: "adreno-540",
  },
  snapdragon845: {
    name: "Qualcomm Snapdragon 845",
    slug: "qualcomm-snapdragon-845",
    maker: "qualcomm",
    cpuName: "Qualcomm Kryo 385 CPU",
    cpuSlug: "qualcomm-kryo-385",
    cores: 8,
    gpuName: "Adreno 630",
    gpuSlug: "adreno-630",
  },
  snapdragon855: {
    name: "Qualcomm Snapdragon 855",
    slug: "qualcomm-snapdragon-855",
    maker: "qualcomm",
    cpuName: "Qualcomm Kryo 485 CPU",
    cpuSlug: "qualcomm-kryo-485",
    cores: 8,
    gpuName: "Adreno 640",
    gpuSlug: "adreno-640",
  },
  snapdragon765g: {
    name: "Qualcomm Snapdragon 765G",
    slug: "qualcomm-snapdragon-765g",
    maker: "qualcomm",
    cpuName: "Qualcomm Kryo 475 CPU",
    cpuSlug: "qualcomm-kryo-475",
    cores: 8,
    gpuName: "Adreno 620",
    gpuSlug: "adreno-620",
  },
  snapdragon865: {
    name: "Qualcomm Snapdragon 865",
    slug: "qualcomm-snapdragon-865",
    maker: "qualcomm",
    cpuName: "Qualcomm Kryo 585 CPU",
    cpuSlug: "qualcomm-kryo-585",
    cores: 8,
    gpuName: "Adreno 650",
    gpuSlug: "adreno-650",
  },
  snapdragon870: {
    name: "Qualcomm Snapdragon 870",
    slug: "qualcomm-snapdragon-870",
    maker: "qualcomm",
    cpuName: "Qualcomm Kryo 585 CPU",
    cpuSlug: "qualcomm-kryo-585",
    cores: 8,
    gpuName: "Adreno 650",
    gpuSlug: "adreno-650",
  },
  snapdragon888: {
    name: "Qualcomm Snapdragon 888",
    slug: "qualcomm-snapdragon-888",
    maker: "qualcomm",
    cpuName: "Qualcomm Kryo 680 CPU",
    cpuSlug: "qualcomm-kryo-680",
    cores: 8,
    gpuName: "Adreno 660",
    gpuSlug: "adreno-660",
  },
  snapdragon8gen1: {
    name: "Qualcomm Snapdragon 8 Gen 1",
    slug: "qualcomm-snapdragon-8-gen-1",
    maker: "qualcomm",
    cpuName: "Qualcomm Kryo 8 Gen 1 CPU",
    cpuSlug: "qualcomm-kryo-8-gen-1",
    cores: 8,
    gpuName: "Adreno 730",
    gpuSlug: "adreno-730",
  },
  exynos8895: {
    name: "Samsung Exynos 8895",
    slug: "samsung-exynos-8895",
    maker: "samsung",
    cpuName: "Samsung M2 / Cortex-A53 CPU",
    cpuSlug: "samsung-exynos-8895-cpu",
    cores: 8,
    gpuName: "Mali-G71 MP20",
    gpuSlug: "mali-g71-mp20",
  },
  exynos9810: {
    name: "Samsung Exynos 9810",
    slug: "samsung-exynos-9810",
    maker: "samsung",
    cpuName: "Samsung M3 / Cortex-A55 CPU",
    cpuSlug: "samsung-exynos-9810-cpu",
    cores: 8,
    gpuName: "Mali-G72 MP18",
    gpuSlug: "mali-g72-mp18",
  },
  exynos9820: {
    name: "Samsung Exynos 9820",
    slug: "samsung-exynos-9820",
    maker: "samsung",
    cpuName: "Samsung M4 / Cortex-A55 CPU",
    cpuSlug: "samsung-exynos-9820-cpu",
    cores: 8,
    gpuName: "Mali-G76 MP12",
    gpuSlug: "mali-g76-mp12",
  },
  exynos990: {
    name: "Samsung Exynos 990",
    slug: "samsung-exynos-990",
    maker: "samsung",
    cpuName: "Samsung M5 / Cortex-A55 CPU",
    cpuSlug: "samsung-exynos-990-cpu",
    cores: 8,
    gpuName: "Mali-G77 MP11",
    gpuSlug: "mali-g77-mp11",
  },
  exynos2100: {
    name: "Samsung Exynos 2100",
    slug: "samsung-exynos-2100",
    maker: "samsung",
    cpuName: "Cortex-X1 / Cortex-A78 CPU",
    cpuSlug: "samsung-exynos-2100-cpu",
    cores: 8,
    gpuName: "Mali-G78 MP14",
    gpuSlug: "mali-g78-mp14",
  },
  exynos2200: {
    name: "Samsung Exynos 2200",
    slug: "samsung-exynos-2200",
    maker: "samsung",
    cpuName: "Cortex-X2 / Cortex-A710 CPU",
    cpuSlug: "samsung-exynos-2200-cpu",
    cores: 8,
    gpuName: "Xclipse 920",
    gpuSlug: "samsung-xclipse-920",
  },
  tensorG1: {
    name: "Google Tensor",
    slug: "google-tensor-g1",
    maker: "google",
    cpuName: "Google Tensor CPU",
    cpuSlug: "google-tensor-g1-cpu",
    cores: 8,
    gpuName: "Mali-G78 MP20",
    gpuSlug: "mali-g78-mp20",
  },
  kirin960: {
    name: "HiSilicon Kirin 960",
    slug: "hisilicon-kirin-960",
    maker: "huawei",
    cpuName: "Kirin 960 Cortex-A73 / Cortex-A53 CPU",
    cpuSlug: "kirin-960-cpu",
    cores: 8,
    gpuName: "Mali-G71 MP8",
    gpuSlug: "mali-g71-mp8",
  },
  kirin970: {
    name: "HiSilicon Kirin 970",
    slug: "hisilicon-kirin-970",
    maker: "huawei",
    cpuName: "Kirin 970 Cortex-A73 / Cortex-A53 CPU",
    cpuSlug: "kirin-970-cpu",
    cores: 8,
    gpuName: "Mali-G72 MP12",
    gpuSlug: "mali-g72-mp12",
  },
  kirin980: {
    name: "HiSilicon Kirin 980",
    slug: "hisilicon-kirin-980",
    maker: "huawei",
    cpuName: "Cortex-A76 / Cortex-A55 CPU",
    cpuSlug: "kirin-980-cpu",
    cores: 8,
    gpuName: "Mali-G76 MP10",
    gpuSlug: "mali-g76-mp10",
  },
  kirin9000: {
    name: "HiSilicon Kirin 9000",
    slug: "hisilicon-kirin-9000",
    maker: "huawei",
    cpuName: "Cortex-A77 / Cortex-A55 CPU",
    cpuSlug: "kirin-9000-cpu",
    cores: 8,
    gpuName: "Mali-G78 MP24",
    gpuSlug: "mali-g78-mp24",
  },
  dimensity1000plus: {
    name: "MediaTek Dimensity 1000+",
    slug: "mediatek-dimensity-1000-plus",
    maker: "mediatek",
    cpuName: "Cortex-A77 / Cortex-A55 CPU",
    cpuSlug: "dimensity-1000-plus-cpu",
    cores: 8,
    gpuName: "Mali-G77 MC9",
    gpuSlug: "mali-g77-mc9",
  },
} satisfies Record<string, Platform>;

type HistoricFact = {
  brandSlug: string;
  familyName: string;
  modelName: string;
  modelSlug: string;
  generation: string;
  announcementDate: string;
  releaseDate: string;
  variantName: string;
  launchPrice: number;
  dimensions: readonly [number, number, number, number];
  display: readonly [
    DisplayTechnology,
    number,
    number,
    number,
    number,
    number?,
  ];
  batteryMah: number;
  cameraMegapixel: number;
  cameraAperture: number;
  platform: keyof typeof PLATFORMS;
  memoryGb: number;
  storageGb: number;
  operatingSystem: OperatingSystem;
  cellular: Extract<Wireless, "cellular4g" | "cellular5g">;
  highlight: string;
  colorName?: string;
  colorHex?: string;
  ingressProtection?: string;
  microSd?: boolean;
};

const SOURCE_BY_BRAND: Record<string, string> = {
  samsung: "https://www.samsung.com/global/galaxy/",
  google: "https://store.google.com/magazine/compare_pixel",
  xiaomi: "https://www.mi.com/global/product-list/phone/",
  oneplus: "https://www.oneplus.com/global/support/spec",
  huawei: "https://consumer.huawei.com/en/support/",
  oppo: "https://www.oppo.com/en/smartphones/",
  sony: "https://www.sony.com/electronics/support",
  asus: "https://www.asus.com/support/",
  vivo: "https://www.vivo.com/en/products",
  motorola: "https://en-us.support.motorola.com/",
};

const FACTS: readonly HistoricFact[] = [
  {
    brandSlug: "samsung",
    familyName: "Galaxy S Series",
    modelName: "Samsung Galaxy S8",
    modelSlug: "samsung-galaxy-s8",
    generation: "Galaxy S8",
    announcementDate: "2017-03-29",
    releaseDate: "2017-04-21",
    variantName: "64GB Midnight Black",
    launchPrice: 720,
    dimensions: [148.9, 68.1, 8, 155],
    display: ["amoled", 5.8, 1440, 2960, 60, 1000],
    batteryMah: 3000,
    cameraMegapixel: 12,
    cameraAperture: 1.7,
    platform: "exynos8895",
    memoryGb: 4,
    storageGb: 64,
    operatingSystem: "android7",
    cellular: "cellular4g",
    highlight:
      "Màn hình Infinity Display 18,5:9 mở đầu giai đoạn thiết kế viền mỏng của Galaxy S.",
    ingressProtection: "IP68",
    microSd: true,
  },
  {
    brandSlug: "samsung",
    familyName: "Galaxy S Series",
    modelName: "Samsung Galaxy S9",
    modelSlug: "samsung-galaxy-s9",
    generation: "Galaxy S9",
    announcementDate: "2018-02-25",
    releaseDate: "2018-03-16",
    variantName: "64GB Midnight Black",
    launchPrice: 720,
    dimensions: [147.7, 68.7, 8.5, 163],
    display: ["amoled", 5.8, 1440, 2960, 60, 1000],
    batteryMah: 3000,
    cameraMegapixel: 12,
    cameraAperture: 1.5,
    platform: "exynos9810",
    memoryGb: 4,
    storageGb: 64,
    operatingSystem: "android8",
    cellular: "cellular4g",
    highlight:
      "Camera khẩu độ kép f/1.5–f/2.4 và loa stereo AKG là các nâng cấp trọng tâm.",
    ingressProtection: "IP68",
    microSd: true,
  },
  {
    brandSlug: "samsung",
    familyName: "Galaxy S Series",
    modelName: "Samsung Galaxy S10",
    modelSlug: "samsung-galaxy-s10",
    generation: "Galaxy S10",
    announcementDate: "2019-02-20",
    releaseDate: "2019-03-08",
    variantName: "128GB Prism Black",
    launchPrice: 900,
    dimensions: [149.9, 70.4, 7.8, 157],
    display: ["amoled", 6.1, 1440, 3040, 60, 1200],
    batteryMah: 3400,
    cameraMegapixel: 12,
    cameraAperture: 1.5,
    platform: "exynos9820",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android9",
    cellular: "cellular4g",
    highlight:
      "Mẫu Galaxy S kỷ niệm 10 năm với camera ba ống kính, Wi‑Fi 6 và cảm biến vân tay siêu âm.",
    ingressProtection: "IP68",
    microSd: true,
  },
  {
    brandSlug: "samsung",
    familyName: "Galaxy S Series",
    modelName: "Samsung Galaxy S20",
    modelSlug: "samsung-galaxy-s20",
    generation: "Galaxy S20",
    announcementDate: "2020-02-11",
    releaseDate: "2020-03-06",
    variantName: "128GB Cosmic Gray",
    launchPrice: 1000,
    dimensions: [151.7, 69.1, 7.9, 163],
    display: ["amoled", 6.2, 1440, 3200, 120, 1200],
    batteryMah: 4000,
    cameraMegapixel: 12,
    cameraAperture: 1.8,
    platform: "exynos990",
    memoryGb: 12,
    storageGb: 128,
    operatingSystem: "android10",
    cellular: "cellular5g",
    highlight:
      "Galaxy S20 đưa 5G và tần số quét 120 Hz vào dòng flagship cỡ nhỏ của Samsung.",
    ingressProtection: "IP68",
    microSd: true,
  },
  {
    brandSlug: "samsung",
    familyName: "Galaxy S Series",
    modelName: "Samsung Galaxy S21",
    modelSlug: "samsung-galaxy-s21",
    generation: "Galaxy S21",
    announcementDate: "2021-01-14",
    releaseDate: "2021-01-29",
    variantName: "128GB Phantom Gray",
    launchPrice: 800,
    dimensions: [151.7, 71.2, 7.9, 169],
    display: ["amoled", 6.2, 1080, 2400, 120, 1300],
    batteryMah: 4000,
    cameraMegapixel: 12,
    cameraAperture: 1.8,
    platform: "exynos2100",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android11",
    cellular: "cellular5g",
    highlight:
      "Thiết kế Contour Cut và chip Exynos 2100/Snapdragon 888 giúp Galaxy S21 mở rộng AI trên thiết bị.",
    ingressProtection: "IP68",
  },
  {
    brandSlug: "samsung",
    familyName: "Galaxy S Series",
    modelName: "Samsung Galaxy S22",
    modelSlug: "samsung-galaxy-s22",
    generation: "Galaxy S22",
    announcementDate: "2022-02-09",
    releaseDate: "2022-02-25",
    variantName: "128GB Phantom Black",
    launchPrice: 800,
    dimensions: [146, 70.6, 7.6, 167],
    display: ["amoled", 6.1, 1080, 2340, 120, 1300],
    batteryMah: 3700,
    cameraMegapixel: 50,
    cameraAperture: 1.8,
    platform: "exynos2200",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android12",
    cellular: "cellular5g",
    highlight:
      "Galaxy S22 nâng camera chính lên 50 MP trong thân máy nhỏ gọn, cùng GPU Xclipse hợp tác AMD.",
    ingressProtection: "IP68",
  },
  {
    brandSlug: "samsung",
    familyName: "Galaxy Z Fold Series",
    modelName: "Samsung Galaxy Fold",
    modelSlug: "samsung-galaxy-fold",
    generation: "Galaxy Fold",
    announcementDate: "2019-02-20",
    releaseDate: "2019-09-06",
    variantName: "512GB Space Silver",
    launchPrice: 1980,
    dimensions: [160.9, 62.9, 15.5, 263],
    display: ["amoled", 7.3, 1536, 2152, 60, 600],
    batteryMah: 4380,
    cameraMegapixel: 12,
    cameraAperture: 1.5,
    platform: "snapdragon855",
    memoryGb: 12,
    storageGb: 512,
    operatingSystem: "android9",
    cellular: "cellular4g",
    highlight:
      "Galaxy Fold là thế hệ điện thoại gập thương mại đầu tiên của Samsung với màn hình chính 7,3 inch.",
    ingressProtection: undefined,
  },
  {
    brandSlug: "samsung",
    familyName: "Galaxy Z Fold Series",
    modelName: "Samsung Galaxy Z Fold3 5G",
    modelSlug: "samsung-galaxy-z-fold3",
    generation: "Galaxy Z Fold3",
    announcementDate: "2021-08-11",
    releaseDate: "2021-08-27",
    variantName: "256GB Phantom Black",
    launchPrice: 1800,
    dimensions: [158.2, 67.1, 16, 271],
    display: ["amoled", 7.6, 1768, 2208, 120, 1200],
    batteryMah: 4400,
    cameraMegapixel: 12,
    cameraAperture: 1.8,
    platform: "snapdragon888",
    memoryGb: 12,
    storageGb: 256,
    operatingSystem: "android11",
    cellular: "cellular5g",
    highlight:
      "Fold3 bổ sung kháng nước IPX8, camera ẩn dưới màn hình và hỗ trợ S Pen cho dòng Fold.",
    ingressProtection: "IPX8",
  },
  {
    brandSlug: "google",
    familyName: "Pixel Series",
    modelName: "Google Pixel",
    modelSlug: "google-pixel",
    generation: "Pixel 1",
    announcementDate: "2016-10-04",
    releaseDate: "2016-10-20",
    variantName: "32GB Quite Black",
    launchPrice: 649,
    dimensions: [143.8, 69.5, 8.5, 143],
    display: ["amoled", 5, 1080, 1920, 60],
    batteryMah: 2770,
    cameraMegapixel: 12.3,
    cameraAperture: 2,
    platform: "snapdragon821",
    memoryGb: 4,
    storageGb: 32,
    operatingSystem: "android7",
    cellular: "cellular4g",
    highlight:
      "Pixel đầu tiên đặt nền tảng cho nhiếp ảnh điện toán và trải nghiệm Android do Google kiểm soát trực tiếp.",
  },
  {
    brandSlug: "google",
    familyName: "Pixel Series",
    modelName: "Google Pixel 2",
    modelSlug: "google-pixel-2",
    generation: "Pixel 2",
    announcementDate: "2017-10-04",
    releaseDate: "2017-10-19",
    variantName: "64GB Just Black",
    launchPrice: 649,
    dimensions: [145.7, 69.7, 7.8, 143],
    display: ["oled", 5, 1080, 1920, 60],
    batteryMah: 2700,
    cameraMegapixel: 12.2,
    cameraAperture: 1.8,
    platform: "snapdragon835",
    memoryGb: 4,
    storageGb: 64,
    operatingSystem: "android8",
    cellular: "cellular4g",
    highlight:
      "Pixel 2 đưa HDR+ và chế độ chân dung bằng một camera trở thành dấu ấn của dòng Pixel.",
  },
  {
    brandSlug: "google",
    familyName: "Pixel Series",
    modelName: "Google Pixel 3",
    modelSlug: "google-pixel-3",
    generation: "Pixel 3",
    announcementDate: "2018-10-09",
    releaseDate: "2018-10-18",
    variantName: "64GB Just Black",
    launchPrice: 799,
    dimensions: [145.6, 68.2, 7.9, 148],
    display: ["oled", 5.5, 1080, 2160, 60],
    batteryMah: 2915,
    cameraMegapixel: 12.2,
    cameraAperture: 1.8,
    platform: "snapdragon845",
    memoryGb: 4,
    storageGb: 64,
    operatingSystem: "android9",
    cellular: "cellular4g",
    highlight:
      "Pixel 3 bổ sung camera góc rộng phía trước và chế độ Night Sight cho chụp thiếu sáng.",
  },
  {
    brandSlug: "google",
    familyName: "Pixel Series",
    modelName: "Google Pixel 4",
    modelSlug: "google-pixel-4",
    generation: "Pixel 4",
    announcementDate: "2019-10-15",
    releaseDate: "2019-10-24",
    variantName: "64GB Just Black",
    launchPrice: 799,
    dimensions: [147.1, 68.8, 8.2, 162],
    display: ["oled", 5.7, 1080, 2280, 90, 444],
    batteryMah: 2800,
    cameraMegapixel: 12.2,
    cameraAperture: 1.7,
    platform: "snapdragon855",
    memoryGb: 6,
    storageGb: 64,
    operatingSystem: "android10",
    cellular: "cellular4g",
    highlight:
      "Pixel 4 kết hợp màn hình 90 Hz, radar Soli và camera tele để tiếp tục ưu tiên ảnh tính toán.",
  },
  {
    brandSlug: "google",
    familyName: "Pixel Series",
    modelName: "Google Pixel 5",
    modelSlug: "google-pixel-5",
    generation: "Pixel 5",
    announcementDate: "2020-09-30",
    releaseDate: "2020-10-15",
    variantName: "128GB Just Black",
    launchPrice: 699,
    dimensions: [144.7, 70.4, 8, 151],
    display: ["oled", 6, 1080, 2340, 90, 700],
    batteryMah: 4080,
    cameraMegapixel: 12.2,
    cameraAperture: 1.7,
    platform: "snapdragon765g",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android11",
    cellular: "cellular5g",
    highlight:
      "Pixel 5 chuyển sang nền tảng 5G tầm trung để cân bằng giá bán, pin và cập nhật phần mềm dài hạn.",
    ingressProtection: "IP68",
  },
  {
    brandSlug: "google",
    familyName: "Pixel Series",
    modelName: "Google Pixel 6",
    modelSlug: "google-pixel-6",
    generation: "Pixel 6",
    announcementDate: "2021-10-19",
    releaseDate: "2021-10-28",
    variantName: "128GB Stormy Black",
    launchPrice: 599,
    dimensions: [158.6, 74.8, 8.9, 207],
    display: ["oled", 6.4, 1080, 2400, 90, 800],
    batteryMah: 4614,
    cameraMegapixel: 50,
    cameraAperture: 1.9,
    platform: "tensorG1",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android12",
    cellular: "cellular5g",
    highlight:
      "Pixel 6 mở đầu kỷ nguyên Google Tensor với thiết kế Camera Bar và xử lý AI tại chỗ.",
    ingressProtection: "IP68",
  },
  {
    brandSlug: "xiaomi",
    familyName: "Xiaomi Mi Series",
    modelName: "Xiaomi Mi 6",
    modelSlug: "xiaomi-mi-6",
    generation: "Mi 6",
    announcementDate: "2017-04-19",
    releaseDate: "2017-04-28",
    variantName: "64GB Black",
    launchPrice: 360,
    dimensions: [145.2, 70.5, 7.5, 168],
    display: ["ips-lcd", 5.15, 1080, 1920, 60],
    batteryMah: 3350,
    cameraMegapixel: 12,
    cameraAperture: 1.8,
    platform: "snapdragon835",
    memoryGb: 6,
    storageGb: 64,
    operatingSystem: "android7",
    cellular: "cellular4g",
    highlight:
      "Mi 6 là flagship Snapdragon 835 nhỏ gọn của Xiaomi với camera tele kép và khung thép không gỉ.",
  },
  {
    brandSlug: "xiaomi",
    familyName: "Xiaomi Mi MIX Series",
    modelName: "Xiaomi Mi MIX 2",
    modelSlug: "xiaomi-mi-mix-2",
    generation: "Mi MIX 2",
    announcementDate: "2017-09-11",
    releaseDate: "2017-09-15",
    variantName: "64GB Black",
    launchPrice: 500,
    dimensions: [151.8, 75.5, 7.7, 185],
    display: ["ips-lcd", 5.99, 1080, 2160, 60],
    batteryMah: 3400,
    cameraMegapixel: 12,
    cameraAperture: 2,
    platform: "snapdragon835",
    memoryGb: 6,
    storageGb: 64,
    operatingSystem: "android7",
    cellular: "cellular4g",
    highlight:
      "Mi MIX 2 tiếp nối thiết kế gần không viền và đưa loa thoại piezoelectric vào dòng thử nghiệm của Xiaomi.",
  },
  {
    brandSlug: "xiaomi",
    familyName: "Xiaomi Mi Series",
    modelName: "Xiaomi Mi 8",
    modelSlug: "xiaomi-mi-8",
    generation: "Mi 8",
    announcementDate: "2018-05-31",
    releaseDate: "2018-06-05",
    variantName: "64GB Black",
    launchPrice: 420,
    dimensions: [154.9, 74.8, 7.6, 175],
    display: ["amoled", 6.21, 1080, 2248, 60, 600],
    batteryMah: 3400,
    cameraMegapixel: 12,
    cameraAperture: 1.8,
    platform: "snapdragon845",
    memoryGb: 6,
    storageGb: 64,
    operatingSystem: "android8",
    cellular: "cellular4g",
    highlight:
      "Mi 8 dùng Snapdragon 845, AMOLED tai thỏ và hệ thống GPS băng tần kép cho định vị chính xác hơn.",
  },
  {
    brandSlug: "xiaomi",
    familyName: "Xiaomi Mi Series",
    modelName: "Xiaomi Mi 9",
    modelSlug: "xiaomi-mi-9",
    generation: "Mi 9",
    announcementDate: "2019-02-20",
    releaseDate: "2019-02-26",
    variantName: "64GB Piano Black",
    launchPrice: 450,
    dimensions: [157.5, 74.7, 7.6, 173],
    display: ["amoled", 6.39, 1080, 2340, 60, 600],
    batteryMah: 3300,
    cameraMegapixel: 48,
    cameraAperture: 1.8,
    platform: "snapdragon855",
    memoryGb: 6,
    storageGb: 64,
    operatingSystem: "android9",
    cellular: "cellular4g",
    highlight:
      "Mi 9 là một trong các flagship Snapdragon 855 giá cạnh tranh, mở rộng camera chính lên 48 MP.",
  },
  {
    brandSlug: "xiaomi",
    familyName: "Xiaomi Mi Series",
    modelName: "Xiaomi Mi 10",
    modelSlug: "xiaomi-mi-10",
    generation: "Mi 10",
    announcementDate: "2020-02-13",
    releaseDate: "2020-02-14",
    variantName: "128GB Twilight Grey",
    launchPrice: 570,
    dimensions: [162.6, 74.8, 9, 208],
    display: ["amoled", 6.67, 1080, 2340, 90, 800],
    batteryMah: 4780,
    cameraMegapixel: 108,
    cameraAperture: 1.7,
    platform: "snapdragon865",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android10",
    cellular: "cellular5g",
    highlight:
      "Mi 10 đưa cảm biến 108 MP, sạc không dây và Snapdragon 865 5G vào dòng flagship Xiaomi.",
  },
  {
    brandSlug: "xiaomi",
    familyName: "Xiaomi Mi Series",
    modelName: "Xiaomi Mi 11",
    modelSlug: "xiaomi-mi-11",
    generation: "Mi 11",
    announcementDate: "2020-12-28",
    releaseDate: "2021-01-01",
    variantName: "128GB Horizon Blue",
    launchPrice: 610,
    dimensions: [164.3, 74.6, 8.1, 196],
    display: ["amoled", 6.81, 1440, 3200, 120, 1500],
    batteryMah: 4600,
    cameraMegapixel: 108,
    cameraAperture: 1.9,
    platform: "snapdragon888",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android11",
    cellular: "cellular5g",
    highlight:
      "Mi 11 ra mắt Snapdragon 888 với màn hình WQHD+ 120 Hz và sạc có dây 55 W.",
  },
  {
    brandSlug: "oneplus",
    familyName: "OnePlus Number Series",
    modelName: "OnePlus 5",
    modelSlug: "oneplus-5",
    generation: "OnePlus 5",
    announcementDate: "2017-06-20",
    releaseDate: "2017-06-27",
    variantName: "64GB Slate Gray",
    launchPrice: 480,
    dimensions: [154.2, 74.1, 7.3, 153],
    display: ["amoled", 5.5, 1080, 1920, 60],
    batteryMah: 3300,
    cameraMegapixel: 16,
    cameraAperture: 1.7,
    platform: "snapdragon835",
    memoryGb: 6,
    storageGb: 64,
    operatingSystem: "android7",
    cellular: "cellular4g",
    highlight:
      "OnePlus 5 tập trung hiệu năng Snapdragon 835, 6 GB RAM và trải nghiệm OxygenOS nhanh gọn.",
  },
  {
    brandSlug: "oneplus",
    familyName: "OnePlus Number Series",
    modelName: "OnePlus 5T",
    modelSlug: "oneplus-5t",
    generation: "OnePlus 5T",
    announcementDate: "2017-11-16",
    releaseDate: "2017-11-21",
    variantName: "64GB Midnight Black",
    launchPrice: 500,
    dimensions: [156.1, 75, 7.3, 162],
    display: ["amoled", 6.01, 1080, 2160, 60],
    batteryMah: 3300,
    cameraMegapixel: 16,
    cameraAperture: 1.7,
    platform: "snapdragon835",
    memoryGb: 6,
    storageGb: 64,
    operatingSystem: "android7",
    cellular: "cellular4g",
    highlight:
      "OnePlus 5T chuyển sang màn hình 18:9, cảm biến vân tay mặt lưng và vẫn giữ cấu hình flagship giá dễ tiếp cận.",
  },
  {
    brandSlug: "oneplus",
    familyName: "OnePlus Number Series",
    modelName: "OnePlus 6",
    modelSlug: "oneplus-6",
    generation: "OnePlus 6",
    announcementDate: "2018-05-16",
    releaseDate: "2018-05-22",
    variantName: "64GB Mirror Black",
    launchPrice: 530,
    dimensions: [155.7, 75.4, 7.8, 177],
    display: ["amoled", 6.28, 1080, 2280, 60],
    batteryMah: 3300,
    cameraMegapixel: 16,
    cameraAperture: 1.7,
    platform: "snapdragon845",
    memoryGb: 6,
    storageGb: 64,
    operatingSystem: "android8",
    cellular: "cellular4g",
    highlight:
      "OnePlus 6 mang mặt lưng kính, Snapdragon 845 và kháng nước thực tế cho dòng máy hiệu năng cao.",
  },
  {
    brandSlug: "oneplus",
    familyName: "OnePlus Number Series",
    modelName: "OnePlus 7 Pro",
    modelSlug: "oneplus-7-pro",
    generation: "OnePlus 7 Pro",
    announcementDate: "2019-05-14",
    releaseDate: "2019-05-17",
    variantName: "256GB Nebula Blue",
    launchPrice: 750,
    dimensions: [162.6, 75.9, 8.8, 206],
    display: ["amoled", 6.67, 1440, 3120, 90, 800],
    batteryMah: 4000,
    cameraMegapixel: 48,
    cameraAperture: 1.6,
    platform: "snapdragon855",
    memoryGb: 8,
    storageGb: 256,
    operatingSystem: "android9",
    cellular: "cellular4g",
    highlight:
      "OnePlus 7 Pro nổi bật với màn hình QHD+ 90 Hz không tai thỏ và camera trước pop-up.",
  },
  {
    brandSlug: "oneplus",
    familyName: "OnePlus Number Series",
    modelName: "OnePlus 8 Pro",
    modelSlug: "oneplus-8-pro",
    generation: "OnePlus 8 Pro",
    announcementDate: "2020-04-14",
    releaseDate: "2020-04-21",
    variantName: "128GB Glacial Green",
    launchPrice: 900,
    dimensions: [165.3, 74.4, 8.5, 199],
    display: ["amoled", 6.78, 1440, 3168, 120, 1300],
    batteryMah: 4510,
    cameraMegapixel: 48,
    cameraAperture: 1.8,
    platform: "snapdragon865",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android10",
    cellular: "cellular5g",
    highlight:
      "OnePlus 8 Pro đưa màn hình 120 Hz, sạc không dây và chuẩn IP68 vào flagship OnePlus.",
    ingressProtection: "IP68",
  },
  {
    brandSlug: "oneplus",
    familyName: "OnePlus Number Series",
    modelName: "OnePlus 9 Pro",
    modelSlug: "oneplus-9-pro",
    generation: "OnePlus 9 Pro",
    announcementDate: "2021-03-23",
    releaseDate: "2021-03-31",
    variantName: "128GB Morning Mist",
    launchPrice: 970,
    dimensions: [163.2, 73.6, 8.7, 197],
    display: ["amoled", 6.7, 1440, 3216, 120, 1300],
    batteryMah: 4500,
    cameraMegapixel: 48,
    cameraAperture: 1.8,
    platform: "snapdragon888",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android11",
    cellular: "cellular5g",
    highlight:
      "OnePlus 9 Pro đánh dấu hợp tác Hasselblad về tinh chỉnh màu ảnh, cùng sạc nhanh Warp Charge 65T.",
    ingressProtection: "IP68",
  },
  {
    brandSlug: "oneplus",
    familyName: "OnePlus Number Series",
    modelName: "OnePlus 10 Pro",
    modelSlug: "oneplus-10-pro",
    generation: "OnePlus 10 Pro",
    announcementDate: "2022-01-11",
    releaseDate: "2022-01-13",
    variantName: "128GB Volcanic Black",
    launchPrice: 900,
    dimensions: [163, 73.9, 8.6, 201],
    display: ["amoled", 6.7, 1440, 3216, 120, 1300],
    batteryMah: 5000,
    cameraMegapixel: 48,
    cameraAperture: 1.8,
    platform: "snapdragon8gen1",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android12",
    cellular: "cellular5g",
    highlight:
      "OnePlus 10 Pro sử dụng Snapdragon 8 Gen 1, pin 5.000 mAh và camera Hasselblad thế hệ hai.",
  },
  {
    brandSlug: "huawei",
    familyName: "Huawei P Series",
    modelName: "Huawei P10",
    modelSlug: "huawei-p10",
    generation: "P10",
    announcementDate: "2017-02-26",
    releaseDate: "2017-03-24",
    variantName: "64GB Graphite Black",
    launchPrice: 680,
    dimensions: [145.3, 69.3, 7, 145],
    display: ["ips-lcd", 5.1, 1080, 1920, 60],
    batteryMah: 3200,
    cameraMegapixel: 12,
    cameraAperture: 2.2,
    platform: "kirin960",
    memoryGb: 4,
    storageGb: 64,
    operatingSystem: "android7",
    cellular: "cellular4g",
    highlight:
      "Huawei P10 tiếp tục camera kép Leica và Kirin 960 trong thân máy nhỏ, mỏng bằng kim loại.",
    microSd: true,
  },
  {
    brandSlug: "huawei",
    familyName: "Huawei Mate Series",
    modelName: "Huawei Mate 10 Pro",
    modelSlug: "huawei-mate-10-pro",
    generation: "Mate 10 Pro",
    announcementDate: "2017-10-16",
    releaseDate: "2017-11-01",
    variantName: "128GB Midnight Blue",
    launchPrice: 800,
    dimensions: [154.2, 74.5, 7.9, 178],
    display: ["oled", 6, 1080, 2160, 60],
    batteryMah: 4000,
    cameraMegapixel: 12,
    cameraAperture: 1.6,
    platform: "kirin970",
    memoryGb: 6,
    storageGb: 128,
    operatingSystem: "android8",
    cellular: "cellular4g",
    highlight:
      "Mate 10 Pro giới thiệu NPU tích hợp của Kirin 970 và pin 4.000 mAh cho dòng Mate.",
    ingressProtection: "IP67",
  },
  {
    brandSlug: "huawei",
    familyName: "Huawei P Series",
    modelName: "Huawei P20 Pro",
    modelSlug: "huawei-p20-pro",
    generation: "P20 Pro",
    announcementDate: "2018-03-27",
    releaseDate: "2018-04-06",
    variantName: "128GB Twilight",
    launchPrice: 1000,
    dimensions: [155, 73.9, 7.8, 180],
    display: ["oled", 6.1, 1080, 2240, 60],
    batteryMah: 4000,
    cameraMegapixel: 40,
    cameraAperture: 1.8,
    platform: "kirin970",
    memoryGb: 6,
    storageGb: 128,
    operatingSystem: "android8",
    cellular: "cellular4g",
    highlight:
      "P20 Pro nổi tiếng với hệ thống ba camera Leica, cảm biến chính 40 MP và Night Mode.",
    ingressProtection: "IP67",
  },
  {
    brandSlug: "huawei",
    familyName: "Huawei P Series",
    modelName: "Huawei P30 Pro",
    modelSlug: "huawei-p30-pro",
    generation: "P30 Pro",
    announcementDate: "2019-03-26",
    releaseDate: "2019-04-06",
    variantName: "128GB Breathing Crystal",
    launchPrice: 900,
    dimensions: [158, 73.4, 8.4, 192],
    display: ["oled", 6.47, 1080, 2340, 60],
    batteryMah: 4200,
    cameraMegapixel: 40,
    cameraAperture: 1.6,
    platform: "kirin980",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android9",
    cellular: "cellular4g",
    highlight:
      "P30 Pro kết hợp camera RYYB 40 MP, tele tiềm vọng 5x và pin lớn cho nhiếp ảnh di động.",
    ingressProtection: "IP68",
  },
  {
    brandSlug: "huawei",
    familyName: "Huawei Mate Series",
    modelName: "Huawei Mate 40 Pro",
    modelSlug: "huawei-mate-40-pro",
    generation: "Mate 40 Pro",
    announcementDate: "2020-10-22",
    releaseDate: "2020-10-30",
    variantName: "256GB Mystic Silver",
    launchPrice: 1200,
    dimensions: [162.9, 75.5, 9.1, 212],
    display: ["oled", 6.76, 1344, 2772, 90, 800],
    batteryMah: 4400,
    cameraMegapixel: 50,
    cameraAperture: 1.9,
    platform: "kirin9000",
    memoryGb: 8,
    storageGb: 256,
    operatingSystem: "android10",
    cellular: "cellular5g",
    highlight:
      "Mate 40 Pro là flagship Kirin 9000 với thiết kế vòng camera Space Ring và tele tiềm vọng.",
    ingressProtection: "IP68",
  },
  {
    brandSlug: "oppo",
    familyName: "OPPO Find X Series",
    modelName: "OPPO Find X",
    modelSlug: "oppo-find-x",
    generation: "Find X",
    announcementDate: "2018-06-19",
    releaseDate: "2018-07-13",
    variantName: "128GB Bordeaux Red",
    launchPrice: 750,
    dimensions: [156.7, 74.2, 9.6, 186],
    display: ["amoled", 6.42, 1080, 2340, 60],
    batteryMah: 3730,
    cameraMegapixel: 16,
    cameraAperture: 2,
    platform: "snapdragon845",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android8",
    cellular: "cellular4g",
    highlight:
      "Find X gây chú ý với cơ chế trượt 3D Stealth, giấu toàn bộ camera khi không sử dụng.",
  },
  {
    brandSlug: "oppo",
    familyName: "OPPO Reno Series",
    modelName: "OPPO Reno",
    modelSlug: "oppo-reno",
    generation: "Reno 1",
    announcementDate: "2019-04-10",
    releaseDate: "2019-04-24",
    variantName: "256GB Ocean Green",
    launchPrice: 450,
    dimensions: [156.6, 74.3, 9, 185],
    display: ["amoled", 6.4, 1080, 2340, 60],
    batteryMah: 3765,
    cameraMegapixel: 48,
    cameraAperture: 1.7,
    platform: "snapdragon710",
    memoryGb: 6,
    storageGb: 256,
    operatingSystem: "android9",
    cellular: "cellular4g",
    highlight:
      "OPPO Reno thế hệ đầu đưa thiết kế camera trước vây cá mập và camera chính 48 MP vào phân khúc cận cao cấp.",
  },
  {
    brandSlug: "oppo",
    familyName: "OPPO Find X Series",
    modelName: "OPPO Find X2 Pro",
    modelSlug: "oppo-find-x2-pro",
    generation: "Find X2 Pro",
    announcementDate: "2020-03-06",
    releaseDate: "2020-03-13",
    variantName: "512GB Orange Vegan Leather",
    launchPrice: 1200,
    dimensions: [164.9, 74.5, 8.8, 200],
    display: ["amoled", 6.7, 1440, 3168, 120, 1200],
    batteryMah: 4260,
    cameraMegapixel: 48,
    cameraAperture: 1.7,
    platform: "snapdragon865",
    memoryGb: 12,
    storageGb: 512,
    operatingSystem: "android10",
    cellular: "cellular5g",
    highlight:
      "Find X2 Pro dùng màn hình QHD+ 120 Hz, sạc SuperVOOC 65 W và camera hai cảm biến 48 MP.",
    ingressProtection: "IP68",
  },
  {
    brandSlug: "oppo",
    familyName: "OPPO Find X Series",
    modelName: "OPPO Find X3 Pro",
    modelSlug: "oppo-find-x3-pro",
    generation: "Find X3 Pro",
    announcementDate: "2021-03-11",
    releaseDate: "2021-03-19",
    variantName: "256GB Gloss Black",
    launchPrice: 1150,
    dimensions: [163.6, 74, 8.3, 193],
    display: ["amoled", 6.7, 1440, 3216, 120, 1300],
    batteryMah: 4500,
    cameraMegapixel: 50,
    cameraAperture: 1.8,
    platform: "snapdragon888",
    memoryGb: 12,
    storageGb: 256,
    operatingSystem: "android11",
    cellular: "cellular5g",
    highlight:
      "Find X3 Pro có màn hình 10-bit, camera hiển vi và thiết kế mặt lưng liền khối.",
    ingressProtection: "IP68",
  },
  {
    brandSlug: "sony",
    familyName: "Sony Xperia XZ Series",
    modelName: "Sony Xperia XZ Premium",
    modelSlug: "sony-xperia-xz-premium",
    generation: "Xperia XZ Premium",
    announcementDate: "2017-02-27",
    releaseDate: "2017-06-01",
    variantName: "64GB Deepsea Black",
    launchPrice: 800,
    dimensions: [156, 77, 7.9, 195],
    display: ["ips-lcd", 5.5, 2160, 3840, 60],
    batteryMah: 3230,
    cameraMegapixel: 19,
    cameraAperture: 2,
    platform: "snapdragon835",
    memoryGb: 4,
    storageGb: 64,
    operatingSystem: "android7",
    cellular: "cellular4g",
    highlight:
      "Xperia XZ Premium kết hợp màn hình 4K HDR, camera Motion Eye và quay siêu chậm 960 fps.",
    ingressProtection: "IP68",
    microSd: true,
  },
  {
    brandSlug: "sony",
    familyName: "Sony Xperia 1 Series",
    modelName: "Sony Xperia 1",
    modelSlug: "sony-xperia-1",
    generation: "Xperia 1",
    announcementDate: "2019-02-25",
    releaseDate: "2019-05-30",
    variantName: "128GB Black",
    launchPrice: 950,
    dimensions: [167, 72, 8.2, 178],
    display: ["oled", 6.5, 1644, 3840, 60],
    batteryMah: 3330,
    cameraMegapixel: 12,
    cameraAperture: 1.6,
    platform: "snapdragon855",
    memoryGb: 6,
    storageGb: 128,
    operatingSystem: "android9",
    cellular: "cellular4g",
    highlight:
      "Xperia 1 mở đầu tỉ lệ 21:9 CinemaWide và hệ thống ba camera lấy cảm hứng từ máy ảnh Sony.",
    ingressProtection: "IP68",
    microSd: true,
  },
  {
    brandSlug: "sony",
    familyName: "Sony Xperia 1 Series",
    modelName: "Sony Xperia 1 II",
    modelSlug: "sony-xperia-1-ii",
    generation: "Xperia 1 II",
    announcementDate: "2020-02-24",
    releaseDate: "2020-06-04",
    variantName: "256GB Black",
    launchPrice: 1200,
    dimensions: [165, 71, 7.9, 181],
    display: ["oled", 6.5, 1644, 3840, 60],
    batteryMah: 4000,
    cameraMegapixel: 12,
    cameraAperture: 1.7,
    platform: "snapdragon865",
    memoryGb: 8,
    storageGb: 256,
    operatingSystem: "android10",
    cellular: "cellular5g",
    highlight:
      "Xperia 1 II bổ sung 5G, AF theo thời gian thực và tinh chỉnh camera từ đội ngũ Alpha.",
    ingressProtection: "IP68",
    microSd: true,
  },
  {
    brandSlug: "asus",
    familyName: "ASUS Zenfone Series",
    modelName: "ASUS Zenfone 5Z",
    modelSlug: "asus-zenfone-5z",
    generation: "Zenfone 5Z",
    announcementDate: "2018-02-27",
    releaseDate: "2018-06-15",
    variantName: "128GB Midnight Blue",
    launchPrice: 500,
    dimensions: [153, 75.7, 7.7, 155],
    display: ["ips-lcd", 6.2, 1080, 2246, 60],
    batteryMah: 3300,
    cameraMegapixel: 12,
    cameraAperture: 1.8,
    platform: "snapdragon845",
    memoryGb: 6,
    storageGb: 128,
    operatingSystem: "android8",
    cellular: "cellular4g",
    highlight:
      "Zenfone 5Z mang Snapdragon 845 và phần mềm ZenUI tối ưu vào mức giá thấp hơn nhiều flagship cùng thời.",
    microSd: true,
  },
  {
    brandSlug: "asus",
    familyName: "ASUS ROG Phone Series",
    modelName: "ASUS ROG Phone",
    modelSlug: "asus-rog-phone",
    generation: "ROG Phone 1",
    announcementDate: "2018-06-04",
    releaseDate: "2018-10-18",
    variantName: "128GB Black",
    launchPrice: 900,
    dimensions: [158.8, 76.2, 8.6, 200],
    display: ["amoled", 6, 1080, 2160, 90],
    batteryMah: 4000,
    cameraMegapixel: 12,
    cameraAperture: 1.8,
    platform: "snapdragon845",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android8",
    cellular: "cellular4g",
    highlight:
      "ROG Phone đầu tiên thiết lập hướng đi gaming phone với màn hình 90 Hz, AirTrigger và phụ kiện AeroActive.",
  },
  {
    brandSlug: "asus",
    familyName: "ASUS ROG Phone Series",
    modelName: "ASUS ROG Phone 3",
    modelSlug: "asus-rog-phone-3",
    generation: "ROG Phone 3",
    announcementDate: "2020-07-22",
    releaseDate: "2020-07-23",
    variantName: "128GB Black",
    launchPrice: 1000,
    dimensions: [171, 78, 9.9, 240],
    display: ["amoled", 6.59, 1080, 2340, 144, 650],
    batteryMah: 6000,
    cameraMegapixel: 64,
    cameraAperture: 1.8,
    platform: "snapdragon865",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android10",
    cellular: "cellular5g",
    highlight:
      "ROG Phone 3 đẩy màn hình 144 Hz, pin 6.000 mAh và Snapdragon 865+ cho trải nghiệm game di động.",
  },
  {
    brandSlug: "vivo",
    familyName: "vivo NEX Series",
    modelName: "vivo NEX",
    modelSlug: "vivo-nex",
    generation: "NEX 1",
    announcementDate: "2018-06-12",
    releaseDate: "2018-06-23",
    variantName: "128GB Black",
    launchPrice: 650,
    dimensions: [162, 77, 8, 199],
    display: ["amoled", 6.59, 1080, 2316, 60],
    batteryMah: 4000,
    cameraMegapixel: 12,
    cameraAperture: 1.8,
    platform: "snapdragon845",
    memoryGb: 8,
    storageGb: 128,
    operatingSystem: "android8",
    cellular: "cellular4g",
    highlight:
      "vivo NEX phổ biến hóa camera trước pop-up và màn hình gần như không viền trong phân khúc flagship.",
  },
  {
    brandSlug: "vivo",
    familyName: "vivo X Series",
    modelName: "vivo X50 Pro",
    modelSlug: "vivo-x50-pro",
    generation: "X50 Pro",
    announcementDate: "2020-06-01",
    releaseDate: "2020-06-12",
    variantName: "256GB Alpha Grey",
    launchPrice: 600,
    dimensions: [158.5, 72.8, 8, 181],
    display: ["amoled", 6.56, 1080, 2376, 90, 1300],
    batteryMah: 4315,
    cameraMegapixel: 48,
    cameraAperture: 1.6,
    platform: "snapdragon765g",
    memoryGb: 8,
    storageGb: 256,
    operatingSystem: "android10",
    cellular: "cellular5g",
    highlight:
      "X50 Pro đưa hệ thống gimbal chống rung vào smartphone, tập trung quay chụp thiếu sáng ổn định.",
  },
  {
    brandSlug: "vivo",
    familyName: "vivo X Series",
    modelName: "vivo X60 Pro",
    modelSlug: "vivo-x60-pro",
    generation: "X60 Pro",
    announcementDate: "2021-03-22",
    releaseDate: "2021-04-02",
    variantName: "256GB Shimmer Blue",
    launchPrice: 800,
    dimensions: [158.6, 73.4, 7.6, 177],
    display: ["amoled", 6.56, 1080, 2376, 120, 1300],
    batteryMah: 4200,
    cameraMegapixel: 48,
    cameraAperture: 1.5,
    platform: "snapdragon870",
    memoryGb: 12,
    storageGb: 256,
    operatingSystem: "android11",
    cellular: "cellular5g",
    highlight:
      "X60 Pro tiếp tục gimbal camera và hợp tác ZEISS để cải thiện màu ảnh cùng hiệu ứng chân dung.",
  },
  {
    brandSlug: "motorola",
    familyName: "Moto Z Series",
    modelName: "Moto Z2 Force",
    modelSlug: "motorola-moto-z2-force",
    generation: "Moto Z2 Force",
    announcementDate: "2017-07-25",
    releaseDate: "2017-08-10",
    variantName: "64GB Super Black",
    launchPrice: 720,
    dimensions: [155.8, 76.2, 6.1, 143],
    display: ["amoled", 5.5, 1440, 2560, 60],
    batteryMah: 2730,
    cameraMegapixel: 12,
    cameraAperture: 2,
    platform: "snapdragon835",
    memoryGb: 4,
    storageGb: 64,
    operatingSystem: "android7",
    cellular: "cellular4g",
    highlight:
      "Moto Z2 Force kết hợp thiết kế mỏng, màn hình ShatterShield và hệ phụ kiện Moto Mods.",
    microSd: true,
  },
  {
    brandSlug: "motorola",
    familyName: "Motorola Razr Series",
    modelName: "Motorola Razr (2019)",
    modelSlug: "motorola-razr-2019",
    generation: "Razr 2019",
    announcementDate: "2019-11-13",
    releaseDate: "2020-02-06",
    variantName: "128GB Noir Black",
    launchPrice: 1500,
    dimensions: [172, 72, 6.9, 205],
    display: ["oled", 6.2, 876, 2142, 60],
    batteryMah: 2510,
    cameraMegapixel: 16,
    cameraAperture: 1.7,
    platform: "snapdragon710",
    memoryGb: 6,
    storageGb: 128,
    operatingSystem: "android9",
    cellular: "cellular4g",
    highlight:
      "Razr 2019 hồi sinh thiết kế vỏ sò kinh điển của Motorola với màn hình OLED gập dọc.",
  },
  {
    brandSlug: "motorola",
    familyName: "Motorola Edge Series",
    modelName: "Motorola Edge 20 Pro",
    modelSlug: "motorola-edge-20-pro",
    generation: "Edge 20 Pro",
    announcementDate: "2021-07-29",
    releaseDate: "2021-08-16",
    variantName: "256GB Midnight Blue",
    launchPrice: 700,
    dimensions: [163, 76, 8, 185],
    display: ["oled", 6.7, 1080, 2400, 144, 576],
    batteryMah: 4500,
    cameraMegapixel: 108,
    cameraAperture: 1.9,
    platform: "snapdragon870",
    memoryGb: 12,
    storageGb: 256,
    operatingSystem: "android11",
    cellular: "cellular5g",
    highlight:
      "Edge 20 Pro kết hợp OLED 144 Hz, camera 108 MP và tele tiềm vọng 5x trong thân máy mỏng.",
  },
] as const;

function slugify(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function descriptionFor(fact: HistoricFact, platform: Platform) {
  return `${fact.modelName} là mẫu ${fact.generation} được công bố vào ${fact.announcementDate} và phát hành từ ${fact.releaseDate}. ${fact.highlight} Phiên bản tham chiếu ${fact.variantName} sử dụng ${platform.name}, ${fact.memoryGb} GB RAM và ${fact.storageGb} GB bộ nhớ trong. Màn hình ${fact.display[1]} inch ${fact.display[0]} có độ phân giải ${fact.display[2]} × ${fact.display[3]} cùng tần số quét ${fact.display[4]} Hz; camera chính ${fact.cameraMegapixel} MP, pin ${fact.batteryMah.toLocaleString("vi-VN")} mAh. Máy xuất xưởng với Android ${fact.operatingSystem.replace("android", "")} và kết nối ${fact.cellular.toUpperCase()}. Hồ sơ lịch sử này chuẩn hóa thông số theo trang lưu trữ của hãng, liên kết chip, CPU, GPU, modem, RAM, bộ nhớ, màn hình, pin, camera và điểm số để so sánh đúng bối cảnh thế hệ.`;
}

export const HISTORIC_CATALOG_DEVICES: CatalogExpansionDeviceSeed[] = FACTS.map(
  (fact) => {
    const platform = PLATFORMS[fact.platform];
    const sourceUrl = SOURCE_BY_BRAND[fact.brandSlug];
    if (!sourceUrl) {
      throw new Error(`Missing manufacturer source for ${fact.modelSlug}.`);
    }
    return {
      brandSlug: fact.brandSlug,
      categorySlug: "smartphone",
      familyName: fact.familyName,
      familySlug: `${fact.brandSlug}-${slugify(fact.familyName)}`,
      modelName: fact.modelName,
      modelSlug: fact.modelSlug,
      announcementDate: fact.announcementDate,
      releaseDate: fact.releaseDate,
      generation: fact.generation,
      description: descriptionFor(fact, platform),
      sourceUrl,
      variantName: fact.variantName,
      colorName: fact.colorName ?? "Black",
      colorHex: fact.colorHex ?? "#202124",
      launchPrice: fact.launchPrice,
      heightMm: fact.dimensions[0],
      widthMm: fact.dimensions[1],
      thicknessMm: fact.dimensions[2],
      weightG: fact.dimensions[3],
      ingressProtection: fact.ingressProtection,
      frameMaterial: "Kim loại và kính",
      backMaterial: "Kính",
      speakerCount: 2,
      headphoneJack: false,
      microSd: fact.microSd ?? false,
      ioNotes:
        "USB-C, Wi-Fi, Bluetooth và kết nối di động theo biến thể thị trường.",
    };
  },
);

export const HISTORIC_CATALOG_MODULES: CatalogModuleSeed[] = FACTS.map(
  (fact) => {
    const platform = PLATFORMS[fact.platform];
    const [technology, size, width, height, refresh, peakNits] = fact.display;
    return {
      modelSlug: fact.modelSlug,
      chipset: {
        ...platform,
      },
      memory: {
        standard: "lpddr4x" as MemoryStandard,
        capacityGb: fact.memoryGb,
        speedMhz: 1866,
      },
      storage: {
        standard: "ufs21" as StorageStandard,
        capacityGb: fact.storageGb,
        expandable: fact.microSd ?? false,
      },
      display: {
        name: `${fact.modelName} display`,
        slug: `${fact.modelSlug}-display`,
        technology,
        size,
        width,
        height,
        refresh,
        peakNits,
      },
      battery: {
        capacityMah: fact.batteryMah,
        wiredW: fact.releaseDate >= "2020-01-01" ? 30 : 18,
      },
      operatingSystem: fact.operatingSystem,
      wireless: ["wifi5", "bluetooth50", fact.cellular],
      ports: [{ standard: "usb-c", count: 1 }],
      camera: {
        megapixel: fact.cameraMegapixel,
        aperture: fact.cameraAperture,
      },
    };
  },
);

export const HISTORIC_CATALOG_ORGANIZATIONS = [
  {
    name: "Motorola Mobility LLC",
    slug: "motorola",
    shortName: "Motorola",
    countryCode: "US",
    websiteUrl: "https://www.motorola.com",
  },
] as const;

const modelSlugs = new Set(
  HISTORIC_CATALOG_DEVICES.map((device) => device.modelSlug),
);
if (
  HISTORIC_CATALOG_DEVICES.length !== 48 ||
  HISTORIC_CATALOG_MODULES.length !== 48 ||
  modelSlugs.size !== 48
) {
  throw new Error("Historic catalog must contain exactly 48 unique devices.");
}

for (const device of HISTORIC_CATALOG_DEVICES) {
  if (
    !device.sourceUrl.startsWith("https://") ||
    device.description.length < 260 ||
    device.launchPrice <= 0 ||
    device.weightG <= 0
  ) {
    throw new Error(
      `Incomplete historical catalog record: ${device.modelSlug}.`,
    );
  }
}
