import type { CatalogModuleSeed } from "./extended-catalog-modules";

export type AdditionalCatalogDeviceSeed = {
  brandSlug: string;
  categorySlug: "smartphone" | "tablet" | "laptop";
  familyName: string;
  familySlug: string;
  modelName: string;
  modelSlug: string;
  announcementDate: string;
  releaseDate: string;
  generation: string;
  description: string;
  variantName: string;
  skuCode?: string;
  colorName: string;
  colorHex: string;
  launchPrice: number;
  heightMm: number;
  widthMm: number;
  thicknessMm: number;
  weightG: number;
  ingressProtection?: string;
  frameMaterial?: string;
  backMaterial?: string;
  speakerCount?: number;
  audioTuning?: string;
  headphoneJack?: boolean;
  microSd?: boolean;
  ioNotes?: string;
};

type ChipsetSeed = CatalogModuleSeed["chipset"];
type DisplaySeed = NonNullable<CatalogModuleSeed["display"]>;
type ModuleDraft = Omit<CatalogModuleSeed, "modelSlug" | "display"> & {
  display: Omit<DisplaySeed, "name" | "slug">;
};

type ExpansionSeed = AdditionalCatalogDeviceSeed & {
  module: ModuleDraft;
};

type ChipsetOptions = {
  threads?: number;
  isa?: string;
  gpuMaker?: string;
  gpuRole?: string;
};

function soc(
  name: string,
  slug: string,
  maker: string,
  cores: number,
  gpuName: string,
  gpuSlug: string,
  options: ChipsetOptions = {},
): ChipsetSeed {
  return {
    name,
    slug,
    maker,
    cpuName: `${name} CPU`,
    cpuSlug: `${slug}-cpu`,
    cores,
    threads: options.threads,
    isa: options.isa,
    gpuName,
    gpuSlug,
    gpuMaker: options.gpuMaker,
    gpuRole: options.gpuRole,
  };
}

function phoneHardware(
  chipset: ChipsetSeed,
  memoryGb: number,
  storageGb: number,
  screen: {
    size: number;
    width: number;
    height: number;
    refresh: number;
    peakNits?: number;
    technology?: DisplaySeed["technology"];
  },
  battery: {
    capacityMah: number;
    wiredW?: number;
    wirelessW?: number;
  },
  options: {
    operatingSystem?: CatalogModuleSeed["operatingSystem"];
    memoryStandard?: CatalogModuleSeed["memory"]["standard"];
    storageStandard?: CatalogModuleSeed["storage"]["standard"];
    port?: CatalogModuleSeed["ports"][number]["standard"];
    cameraMegapixel?: number;
    cameraAperture?: number;
  } = {},
): ModuleDraft {
  return {
    chipset,
    memory: {
      standard: options.memoryStandard ?? "lpddr5x",
      capacityGb: memoryGb,
      speedMhz: 4266,
    },
    storage: {
      standard: options.storageStandard ?? "ufs4",
      capacityGb: storageGb,
    },
    display: {
      technology: screen.technology ?? "ltpo-oled",
      size: screen.size,
      width: screen.width,
      height: screen.height,
      refresh: screen.refresh,
      peakNits: screen.peakNits,
    },
    battery,
    operatingSystem: options.operatingSystem ?? "android15",
    wireless: ["wifi7", "bluetooth53", "cellular5g"],
    ports: [{ standard: options.port ?? "usb-c", count: 1 }],
    camera: {
      megapixel: options.cameraMegapixel ?? 50,
      aperture: options.cameraAperture ?? 1.8,
    },
  };
}

function laptopHardware(
  chipset: ChipsetSeed,
  memoryGb: number,
  storageGb: number,
  screen: {
    size: number;
    width: number;
    height: number;
    refresh: number;
    peakNits?: number;
    technology?: DisplaySeed["technology"];
  },
  batteryWh: number,
  options: {
    operatingSystem?: CatalogModuleSeed["operatingSystem"];
    memoryStandard?: CatalogModuleSeed["memory"]["standard"];
    storageStandard?: CatalogModuleSeed["storage"]["standard"];
    ports?: CatalogModuleSeed["ports"];
  } = {},
): ModuleDraft {
  return {
    chipset,
    memory: {
      standard: options.memoryStandard ?? "ddr5",
      capacityGb: memoryGb,
      speedMhz: 6400,
    },
    storage: {
      standard: options.storageStandard ?? "nvme",
      capacityGb: storageGb,
    },
    display: {
      technology: screen.technology ?? "oled",
      size: screen.size,
      width: screen.width,
      height: screen.height,
      refresh: screen.refresh,
      peakNits: screen.peakNits,
    },
    battery: {
      capacityMah: Math.round((batteryWh / 11.55) * 1000),
      energyWh: batteryWh,
      wiredW: 100,
    },
    operatingSystem: options.operatingSystem ?? "windows11",
    wireless: ["wifi7", "bluetooth54"],
    ports: options.ports ?? [
      { standard: "usb4", count: 2 },
      { standard: "hdmi21", count: 1 },
    ],
    camera: { megapixel: 2, aperture: 2 },
  };
}

function tabletHardware(
  chipset: ChipsetSeed,
  memoryGb: number,
  storageGb: number,
  screen: {
    size: number;
    width: number;
    height: number;
    refresh: number;
    peakNits?: number;
    technology?: DisplaySeed["technology"];
  },
  battery: { capacityMah: number; wiredW?: number },
  options: {
    operatingSystem?: CatalogModuleSeed["operatingSystem"];
    memoryStandard?: CatalogModuleSeed["memory"]["standard"];
    storageStandard?: CatalogModuleSeed["storage"]["standard"];
  } = {},
): ModuleDraft {
  return {
    ...phoneHardware(chipset, memoryGb, storageGb, screen, battery, {
      operatingSystem: options.operatingSystem ?? "android15",
      memoryStandard: options.memoryStandard,
      storageStandard: options.storageStandard,
      cameraMegapixel: 13,
      cameraAperture: 2,
    }),
    wireless: ["wifi7", "bluetooth53"],
  };
}

const A15 = soc(
  "Apple A15 Bionic",
  "apple-a15-bionic",
  "apple",
  6,
  "Apple GPU (A15)",
  "apple-gpu-a15",
);
const A16 = soc(
  "Apple A16 Bionic",
  "apple-a16-bionic",
  "apple",
  6,
  "Apple GPU (A16)",
  "apple-gpu-a16",
);
const A18 = soc(
  "Apple A18",
  "apple-a18",
  "apple",
  6,
  "Apple GPU (A18)",
  "apple-gpu-a18",
);
const A18_PRO = soc(
  "Apple A18 Pro",
  "apple-a18-pro",
  "apple",
  6,
  "Apple GPU (A18 Pro)",
  "apple-gpu-a18-pro",
);
const APPLE_M2 = soc(
  "Apple M2",
  "apple-m2",
  "apple",
  8,
  "Apple M2 GPU",
  "apple-m2-gpu",
);
const APPLE_M4 = soc(
  "Apple M4",
  "apple-m4",
  "apple",
  10,
  "Apple M4 GPU",
  "apple-m4-gpu",
);
const APPLE_M4_MAX = soc(
  "Apple M4 Max",
  "apple-m4-max",
  "apple",
  16,
  "Apple M4 Max GPU",
  "apple-m4-max-gpu",
);
const SNAPDRAGON_8_ELITE = soc(
  "Snapdragon 8 Elite",
  "snapdragon-8-elite",
  "qualcomm",
  8,
  "Adreno 830",
  "adreno-830",
);
const SNAPDRAGON_8_GEN_3 = soc(
  "Snapdragon 8 Gen 3",
  "snapdragon-8-gen-3",
  "qualcomm",
  8,
  "Adreno 750",
  "adreno-750",
);
const SNAPDRAGON_8_GEN_2 = soc(
  "Snapdragon 8 Gen 2",
  "snapdragon-8-gen-2",
  "qualcomm",
  8,
  "Adreno 740",
  "adreno-740",
);
const SNAPDRAGON_8S_GEN_3 = soc(
  "Snapdragon 8s Gen 3",
  "snapdragon-8s-gen-3",
  "qualcomm",
  8,
  "Adreno 735",
  "adreno-735",
);
const SNAPDRAGON_7_PLUS_GEN_3 = soc(
  "Snapdragon 7+ Gen 3",
  "snapdragon-7-plus-gen-3",
  "qualcomm",
  8,
  "Adreno 732",
  "adreno-732",
);
const SNAPDRAGON_7_GEN_3 = soc(
  "Snapdragon 7 Gen 3",
  "snapdragon-7-gen-3",
  "qualcomm",
  8,
  "Adreno 720",
  "adreno-720",
);
const SNAPDRAGON_7S_GEN_3 = soc(
  "Snapdragon 7s Gen 3",
  "snapdragon-7s-gen-3",
  "qualcomm",
  8,
  "Adreno 810",
  "adreno-810",
);
const SNAPDRAGON_X_ELITE = soc(
  "Snapdragon X Elite X1E-80-100",
  "snapdragon-x-elite-x1e-80-100",
  "qualcomm",
  12,
  "Qualcomm Adreno X1-85",
  "qualcomm-adreno-x1-85",
);
const EXYNOS_2400E = soc(
  "Exynos 2400e",
  "exynos-2400e",
  "samsung",
  10,
  "Samsung Xclipse 940",
  "samsung-xclipse-940",
);
const EXYNOS_1480 = soc(
  "Exynos 1480",
  "exynos-1480",
  "samsung",
  8,
  "Samsung Xclipse 530",
  "samsung-xclipse-530",
);
const EXYNOS_1380 = soc(
  "Exynos 1380",
  "exynos-1380",
  "samsung",
  8,
  "Mali-G68 MP5",
  "mali-g68-mp5",
);
const TENSOR_G3 = soc(
  "Google Tensor G3",
  "google-tensor-g3",
  "google",
  9,
  "Mali-G715 MP7",
  "mali-g715-mp7",
);
const TENSOR_G4 = soc(
  "Google Tensor G4",
  "google-tensor-g4",
  "google",
  8,
  "Mali-G715 MP7",
  "mali-g715-mp7",
);
const DIMENSITY_9400 = soc(
  "MediaTek Dimensity 9400",
  "mediatek-dimensity-9400",
  "mediatek",
  8,
  "Arm Immortalis-G925",
  "immortalis-g925",
);
const DIMENSITY_9300_PLUS = soc(
  "MediaTek Dimensity 9300+",
  "mediatek-dimensity-9300-plus",
  "mediatek",
  8,
  "Arm Immortalis-G720",
  "immortalis-g720",
);
const DIMENSITY_9200 = soc(
  "MediaTek Dimensity 9200",
  "mediatek-dimensity-9200",
  "mediatek",
  8,
  "Arm Immortalis-G715",
  "immortalis-g715",
);
const DIMENSITY_8350 = soc(
  "MediaTek Dimensity 8350",
  "mediatek-dimensity-8350",
  "mediatek",
  8,
  "Mali-G615 MC6",
  "mali-g615-mc6",
);
const DIMENSITY_7300 = soc(
  "MediaTek Dimensity 7300",
  "mediatek-dimensity-7300",
  "mediatek",
  8,
  "Mali-G615 MC2",
  "mali-g615-mc2",
);
const DIMENSITY_9000 = soc(
  "MediaTek Dimensity 9000",
  "mediatek-dimensity-9000",
  "mediatek",
  8,
  "Mali-G710 MC10",
  "mali-g710-mc10",
);
const KIRIN_9010 = soc(
  "Kirin 9010",
  "kirin-9010",
  "huawei",
  12,
  "Maleoon 910",
  "maleoon-910",
);
const KIRIN_9020 = soc(
  "Kirin 9020",
  "kirin-9020",
  "huawei",
  12,
  "Maleoon 920",
  "maleoon-920",
);

const CORE_ULTRA_7_155H = soc(
  "Intel Core Ultra 7 155H",
  "intel-core-ultra-7-155h",
  "intel",
  16,
  "Intel Arc Graphics",
  "intel-arc-graphics",
  { threads: 22, isa: "x86-64" },
);
const CORE_ULTRA_7_258V = soc(
  "Intel Core Ultra 7 258V",
  "intel-core-ultra-7-258v",
  "intel",
  8,
  "Intel Arc 140V",
  "intel-arc-140v",
  { threads: 8, isa: "x86-64" },
);
const CORE_ULTRA_9_185H_RTX4070 = soc(
  "Intel Core Ultra 9 185H",
  "intel-core-ultra-9-185h",
  "intel",
  16,
  "NVIDIA GeForce RTX 4070 Laptop GPU",
  "nvidia-rtx-4070-laptop",
  {
    threads: 22,
    isa: "x86-64",
    gpuMaker: "nvidia",
    gpuRole: "discrete",
  },
);
const CORE_ULTRA_9_285HX_RTX5080 = soc(
  "Intel Core Ultra 9 285HX",
  "intel-core-ultra-9-285hx",
  "intel",
  24,
  "NVIDIA GeForce RTX 5080 Laptop GPU",
  "nvidia-rtx-5080-laptop",
  {
    threads: 24,
    isa: "x86-64",
    gpuMaker: "nvidia",
    gpuRole: "discrete",
  },
);
const RYZEN_7_8845HS_RTX4060 = soc(
  "AMD Ryzen 7 8845HS",
  "amd-ryzen-7-8845hs",
  "amd",
  8,
  "NVIDIA GeForce RTX 4060 Laptop GPU",
  "nvidia-geforce-rtx-4060-laptop",
  {
    threads: 16,
    isa: "x86-64",
    gpuMaker: "nvidia",
    gpuRole: "discrete",
  },
);
const RYZEN_AI_9_HX370 = soc(
  "AMD Ryzen AI 9 HX 370",
  "amd-ryzen-ai-9-hx-370",
  "amd",
  12,
  "AMD Radeon 890M",
  "amd-radeon-890m",
  { threads: 24, isa: "x86-64" },
);
const RYZEN_AI_9_HX370_RTX4070 = soc(
  "AMD Ryzen AI 9 HX 370",
  "amd-ryzen-ai-9-hx-370",
  "amd",
  12,
  "NVIDIA GeForce RTX 4070 Laptop GPU",
  "nvidia-rtx-4070-laptop",
  {
    threads: 24,
    isa: "x86-64",
    gpuMaker: "nvidia",
    gpuRole: "discrete",
  },
);

const EXPANSION: ExpansionSeed[] = [
  // 30 điện thoại
  {
    brandSlug: "apple",
    categorySlug: "smartphone",
    familyName: "iPhone 16 Series",
    familySlug: "iphone-16-plus-series",
    modelName: "iPhone 16 Plus",
    modelSlug: "iphone-16-plus",
    announcementDate: "2024-09-09",
    releaseDate: "2024-09-20",
    generation: "Gen 18",
    description:
      "Điện thoại màn hình lớn, pin lâu với chip A18 và Camera Control.",
    variantName: "128GB Teal",
    colorName: "Teal",
    colorHex: "#8DB9B2",
    launchPrice: 899,
    heightMm: 160.9,
    widthMm: 77.8,
    thicknessMm: 7.8,
    weightG: 199,
    ingressProtection: "IP68",
    frameMaterial: "Nhôm",
    backMaterial: "Kính pha màu",
    speakerCount: 2,
    module: phoneHardware(
      A18,
      8,
      128,
      { size: 6.7, width: 1290, height: 2796, refresh: 60, peakNits: 2000 },
      { capacityMah: 4674, wiredW: 27, wirelessW: 25 },
      { operatingSystem: "ios18", storageStandard: "apple-nvme" },
    ),
  },
  {
    brandSlug: "apple",
    categorySlug: "smartphone",
    familyName: "iPhone 16 Pro Series",
    familySlug: "iphone-16-pro-max-series",
    modelName: "iPhone 16 Pro Max",
    modelSlug: "iphone-16-pro-max",
    announcementDate: "2024-09-09",
    releaseDate: "2024-09-20",
    generation: "Gen 18 Pro",
    description:
      "Mẫu iPhone cao cấp cỡ lớn với A18 Pro, khung titan và camera chụp xa 5x.",
    variantName: "256GB Desert Titanium",
    colorName: "Desert Titanium",
    colorHex: "#B6A28E",
    launchPrice: 1199,
    heightMm: 163,
    widthMm: 77.6,
    thicknessMm: 8.3,
    weightG: 227,
    ingressProtection: "IP68",
    frameMaterial: "Titan",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      A18_PRO,
      8,
      256,
      {
        size: 6.9,
        width: 1320,
        height: 2868,
        refresh: 120,
        peakNits: 2000,
      },
      { capacityMah: 4685, wiredW: 30, wirelessW: 25 },
      {
        operatingSystem: "ios18",
        storageStandard: "apple-nvme",
        cameraMegapixel: 48,
        cameraAperture: 1.8,
      },
    ),
  },
  {
    brandSlug: "apple",
    categorySlug: "smartphone",
    familyName: "iPhone 15 Series",
    familySlug: "iphone-15-series-expanded",
    modelName: "iPhone 15",
    modelSlug: "iphone-15",
    announcementDate: "2023-09-12",
    releaseDate: "2023-09-22",
    generation: "Gen 17",
    description:
      "iPhone phổ thông với Dynamic Island, cổng USB-C và camera chính 48 MP.",
    variantName: "128GB Pink",
    colorName: "Pink",
    colorHex: "#E9C8CC",
    launchPrice: 799,
    heightMm: 147.6,
    widthMm: 71.6,
    thicknessMm: 7.8,
    weightG: 171,
    ingressProtection: "IP68",
    frameMaterial: "Nhôm",
    backMaterial: "Kính pha màu",
    speakerCount: 2,
    module: phoneHardware(
      A16,
      6,
      128,
      { size: 6.1, width: 1179, height: 2556, refresh: 60, peakNits: 2000 },
      { capacityMah: 3349, wiredW: 20, wirelessW: 15 },
      { operatingSystem: "ios18", storageStandard: "apple-nvme" },
    ),
  },
  {
    brandSlug: "apple",
    categorySlug: "smartphone",
    familyName: "iPhone SE Series",
    familySlug: "iphone-se-3-series",
    modelName: "iPhone SE (thế hệ 3)",
    modelSlug: "iphone-se-3",
    announcementDate: "2022-03-08",
    releaseDate: "2022-03-18",
    generation: "SE 3",
    description: "iPhone nhỏ gọn có Touch ID, chip A15 Bionic và kết nối 5G.",
    variantName: "64GB PRODUCT(RED)",
    colorName: "PRODUCT(RED)",
    colorHex: "#B8242A",
    launchPrice: 429,
    heightMm: 138.4,
    widthMm: 67.3,
    thicknessMm: 7.3,
    weightG: 144,
    ingressProtection: "IP67",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      A15,
      4,
      64,
      {
        size: 4.7,
        width: 750,
        height: 1334,
        refresh: 60,
        peakNits: 625,
        technology: "ips-lcd",
      },
      { capacityMah: 2018, wiredW: 20, wirelessW: 7.5 },
      {
        operatingSystem: "ios18",
        storageStandard: "apple-nvme",
        cameraMegapixel: 12,
      },
    ),
  },
  {
    brandSlug: "apple",
    categorySlug: "smartphone",
    familyName: "iPhone 14 Series",
    familySlug: "iphone-14-series-expanded",
    modelName: "iPhone 14",
    modelSlug: "iphone-14",
    announcementDate: "2022-09-07",
    releaseDate: "2022-09-16",
    generation: "Gen 16",
    description:
      "iPhone 6,1 inch cân bằng với A15 Bionic, camera kép và tính năng an toàn.",
    variantName: "128GB Blue",
    colorName: "Blue",
    colorHex: "#A7C1D9",
    launchPrice: 799,
    heightMm: 146.7,
    widthMm: 71.5,
    thicknessMm: 7.8,
    weightG: 172,
    ingressProtection: "IP68",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      A15,
      6,
      128,
      { size: 6.1, width: 1170, height: 2532, refresh: 60, peakNits: 1200 },
      { capacityMah: 3279, wiredW: 20, wirelessW: 15 },
      {
        operatingSystem: "ios18",
        storageStandard: "apple-nvme",
        cameraMegapixel: 12,
      },
    ),
  },
  {
    brandSlug: "samsung",
    categorySlug: "smartphone",
    familyName: "Galaxy S25 Series",
    familySlug: "galaxy-s25-series-expanded",
    modelName: "Samsung Galaxy S25",
    modelSlug: "galaxy-s25",
    announcementDate: "2025-01-22",
    releaseDate: "2025-02-07",
    generation: "S25",
    description:
      "Điện thoại cao cấp nhỏ gọn với Snapdragon 8 Elite và bộ tính năng Galaxy AI.",
    variantName: "12GB/256GB Navy",
    colorName: "Navy",
    colorHex: "#44546A",
    launchPrice: 799.99,
    heightMm: 146.9,
    widthMm: 70.5,
    thicknessMm: 7.2,
    weightG: 162,
    ingressProtection: "IP68",
    frameMaterial: "Armor Aluminum",
    backMaterial: "Gorilla Glass Victus 2",
    speakerCount: 2,
    module: phoneHardware(
      SNAPDRAGON_8_ELITE,
      12,
      256,
      { size: 6.2, width: 1080, height: 2340, refresh: 120, peakNits: 2600 },
      { capacityMah: 4000, wiredW: 25, wirelessW: 15 },
    ),
  },
  {
    brandSlug: "samsung",
    categorySlug: "smartphone",
    familyName: "Galaxy S25 Series",
    familySlug: "galaxy-s25-plus-series",
    modelName: "Samsung Galaxy S25+",
    modelSlug: "galaxy-s25-plus",
    announcementDate: "2025-01-22",
    releaseDate: "2025-02-07",
    generation: "S25+",
    description:
      "Mẫu Galaxy S cỡ lớn với màn hình QHD+, pin 4900 mAh và hiệu năng cao.",
    variantName: "12GB/256GB Icyblue",
    colorName: "Icyblue",
    colorHex: "#CAD5DC",
    launchPrice: 999.99,
    heightMm: 158.4,
    widthMm: 75.8,
    thicknessMm: 7.3,
    weightG: 190,
    ingressProtection: "IP68",
    frameMaterial: "Armor Aluminum",
    backMaterial: "Gorilla Glass Victus 2",
    speakerCount: 2,
    module: phoneHardware(
      SNAPDRAGON_8_ELITE,
      12,
      256,
      { size: 6.7, width: 1440, height: 3120, refresh: 120, peakNits: 2600 },
      { capacityMah: 4900, wiredW: 45, wirelessW: 15 },
    ),
  },
  {
    brandSlug: "samsung",
    categorySlug: "smartphone",
    familyName: "Galaxy S24 FE Series",
    familySlug: "galaxy-s24-fe-series",
    modelName: "Samsung Galaxy S24 FE",
    modelSlug: "galaxy-s24-fe",
    announcementDate: "2024-09-26",
    releaseDate: "2024-10-03",
    generation: "S24 FE",
    description:
      "Mẫu Fan Edition màn hình lớn với Exynos 2400e và camera chụp xa.",
    variantName: "8GB/256GB Blue",
    colorName: "Blue",
    colorHex: "#9BB5C9",
    launchPrice: 709.99,
    heightMm: 162,
    widthMm: 77.3,
    thicknessMm: 8,
    weightG: 213,
    ingressProtection: "IP68",
    frameMaterial: "Nhôm",
    backMaterial: "Gorilla Glass Victus+",
    speakerCount: 2,
    module: phoneHardware(
      EXYNOS_2400E,
      8,
      256,
      {
        size: 6.7,
        width: 1080,
        height: 2340,
        refresh: 120,
        peakNits: 1900,
        technology: "amoled",
      },
      { capacityMah: 4700, wiredW: 25, wirelessW: 15 },
    ),
  },
  {
    brandSlug: "samsung",
    categorySlug: "smartphone",
    familyName: "Galaxy Z Flip6 Series",
    familySlug: "galaxy-z-flip6-series",
    modelName: "Samsung Galaxy Z Flip6",
    modelSlug: "galaxy-z-flip6",
    announcementDate: "2024-07-10",
    releaseDate: "2024-07-24",
    generation: "Flip6",
    description:
      "Điện thoại gập vỏ sò nhỏ gọn với màn hình phụ và camera chính 50 MP.",
    variantName: "12GB/256GB Blue",
    colorName: "Blue",
    colorHex: "#AFC7D5",
    launchPrice: 1099.99,
    heightMm: 165.1,
    widthMm: 71.9,
    thicknessMm: 6.9,
    weightG: 187,
    ingressProtection: "IP48",
    frameMaterial: "Armor Aluminum",
    backMaterial: "Gorilla Glass Victus 2",
    speakerCount: 2,
    module: phoneHardware(
      SNAPDRAGON_8_GEN_3,
      12,
      256,
      { size: 6.7, width: 1080, height: 2640, refresh: 120, peakNits: 2600 },
      { capacityMah: 4000, wiredW: 25, wirelessW: 15 },
    ),
  },
  {
    brandSlug: "samsung",
    categorySlug: "smartphone",
    familyName: "Galaxy A Series",
    familySlug: "galaxy-a55-series",
    modelName: "Samsung Galaxy A55 5G",
    modelSlug: "galaxy-a55-5g",
    announcementDate: "2024-03-11",
    releaseDate: "2024-03-15",
    generation: "A55",
    description:
      "Điện thoại tầm trung khung kim loại với màn hình AMOLED và chống nước IP67.",
    variantName: "8GB/256GB Awesome Navy",
    colorName: "Awesome Navy",
    colorHex: "#252A38",
    launchPrice: 449,
    heightMm: 161.1,
    widthMm: 77.4,
    thicknessMm: 8.2,
    weightG: 213,
    ingressProtection: "IP67",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    microSd: true,
    module: phoneHardware(
      EXYNOS_1480,
      8,
      256,
      {
        size: 6.6,
        width: 1080,
        height: 2340,
        refresh: 120,
        peakNits: 1000,
        technology: "amoled",
      },
      { capacityMah: 5000, wiredW: 25 },
      { storageStandard: "ufs31" },
    ),
  },
  {
    brandSlug: "samsung",
    categorySlug: "smartphone",
    familyName: "Galaxy A Series",
    familySlug: "galaxy-a35-series",
    modelName: "Samsung Galaxy A35 5G",
    modelSlug: "galaxy-a35-5g",
    announcementDate: "2024-03-11",
    releaseDate: "2024-03-15",
    generation: "A35",
    description:
      "Điện thoại tầm trung màn hình AMOLED 120 Hz, pin 5000 mAh và IP67.",
    variantName: "8GB/256GB Awesome Lilac",
    colorName: "Awesome Lilac",
    colorHex: "#D3C7E5",
    launchPrice: 399,
    heightMm: 161.7,
    widthMm: 78,
    thicknessMm: 8.2,
    weightG: 209,
    ingressProtection: "IP67",
    frameMaterial: "Nhựa",
    backMaterial: "Kính",
    speakerCount: 2,
    microSd: true,
    module: phoneHardware(
      EXYNOS_1380,
      8,
      256,
      {
        size: 6.6,
        width: 1080,
        height: 2340,
        refresh: 120,
        peakNits: 1000,
        technology: "amoled",
      },
      { capacityMah: 5000, wiredW: 25 },
      { storageStandard: "ufs31" },
    ),
  },
  {
    brandSlug: "google",
    categorySlug: "smartphone",
    familyName: "Pixel 9 Series",
    familySlug: "pixel-9-series-expanded",
    modelName: "Google Pixel 9",
    modelSlug: "pixel-9",
    announcementDate: "2024-08-13",
    releaseDate: "2024-08-22",
    generation: "Gen 9",
    description: "Pixel nhỏ gọn với Tensor G4, camera kép và bảy năm cập nhật.",
    variantName: "12GB/128GB Peony",
    colorName: "Peony",
    colorHex: "#E7B4C5",
    launchPrice: 799,
    heightMm: 152.8,
    widthMm: 72,
    thicknessMm: 8.5,
    weightG: 198,
    ingressProtection: "IP68",
    frameMaterial: "Nhôm",
    backMaterial: "Gorilla Glass Victus 2",
    speakerCount: 2,
    module: phoneHardware(
      TENSOR_G4,
      12,
      128,
      { size: 6.3, width: 1080, height: 2424, refresh: 120, peakNits: 2700 },
      { capacityMah: 4700, wiredW: 27, wirelessW: 15 },
      { storageStandard: "ufs31" },
    ),
  },
  {
    brandSlug: "google",
    categorySlug: "smartphone",
    familyName: "Pixel 9 Pro Fold Series",
    familySlug: "pixel-9-pro-fold-series",
    modelName: "Google Pixel 9 Pro Fold",
    modelSlug: "pixel-9-pro-fold",
    announcementDate: "2024-08-13",
    releaseDate: "2024-09-04",
    generation: "Fold 2",
    description:
      "Pixel gập dạng sách với màn hình trong 8 inch và hệ thống camera linh hoạt.",
    variantName: "16GB/256GB Obsidian",
    colorName: "Obsidian",
    colorHex: "#252525",
    launchPrice: 1799,
    heightMm: 155.2,
    widthMm: 150.2,
    thicknessMm: 5.1,
    weightG: 257,
    ingressProtection: "IPX8",
    frameMaterial: "Nhôm",
    backMaterial: "Gorilla Glass Victus 2",
    speakerCount: 2,
    module: phoneHardware(
      TENSOR_G4,
      16,
      256,
      { size: 8, width: 2076, height: 2152, refresh: 120, peakNits: 2700 },
      { capacityMah: 4650, wiredW: 21, wirelessW: 7.5 },
      { storageStandard: "ufs31", cameraMegapixel: 48 },
    ),
  },
  {
    brandSlug: "google",
    categorySlug: "smartphone",
    familyName: "Pixel 8 Series",
    familySlug: "pixel-8a-series",
    modelName: "Google Pixel 8a",
    modelSlug: "pixel-8a",
    announcementDate: "2024-05-07",
    releaseDate: "2024-05-14",
    generation: "Gen 8a",
    description:
      "Pixel tầm trung với Tensor G3, màn hình 120 Hz và camera xử lý bằng AI.",
    variantName: "8GB/128GB Bay",
    colorName: "Bay",
    colorHex: "#9CC5E3",
    launchPrice: 499,
    heightMm: 152.1,
    widthMm: 72.7,
    thicknessMm: 8.9,
    weightG: 188,
    ingressProtection: "IP67",
    frameMaterial: "Nhôm",
    backMaterial: "Vật liệu tổng hợp",
    speakerCount: 2,
    module: phoneHardware(
      TENSOR_G3,
      8,
      128,
      { size: 6.1, width: 1080, height: 2400, refresh: 120, peakNits: 2000 },
      { capacityMah: 4492, wiredW: 18, wirelessW: 7.5 },
      { storageStandard: "ufs31", cameraMegapixel: 64 },
    ),
  },
  {
    brandSlug: "xiaomi",
    categorySlug: "smartphone",
    familyName: "Xiaomi 14T Series",
    familySlug: "xiaomi-14t-pro-series",
    modelName: "Xiaomi 14T Pro",
    modelSlug: "xiaomi-14t-pro",
    announcementDate: "2024-09-26",
    releaseDate: "2024-09-26",
    generation: "14T Pro",
    description:
      "Điện thoại hiệu năng cao với Dimensity 9300+, camera Leica và sạc 120 W.",
    variantName: "12GB/512GB Titan Gray",
    colorName: "Titan Gray",
    colorHex: "#73777A",
    launchPrice: 899,
    heightMm: 160.4,
    widthMm: 75.1,
    thicknessMm: 8.4,
    weightG: 209,
    ingressProtection: "IP68",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      DIMENSITY_9300_PLUS,
      12,
      512,
      {
        size: 6.7,
        width: 1220,
        height: 2712,
        refresh: 144,
        peakNits: 4000,
        technology: "amoled",
      },
      { capacityMah: 5000, wiredW: 120, wirelessW: 50 },
    ),
  },
  {
    brandSlug: "xiaomi",
    categorySlug: "smartphone",
    familyName: "Redmi Note 14 Series",
    familySlug: "redmi-note-14-pro-plus-series",
    modelName: "Redmi Note 14 Pro+ 5G",
    modelSlug: "redmi-note-14-pro-plus",
    announcementDate: "2024-09-26",
    releaseDate: "2024-09-26",
    generation: "Note 14",
    description:
      "Điện thoại tầm trung cao cấp với camera 200 MP, màn hình AMOLED và sạc nhanh.",
    variantName: "12GB/256GB Frost Blue",
    colorName: "Frost Blue",
    colorHex: "#BFD0DC",
    launchPrice: 449,
    heightMm: 162.5,
    widthMm: 74.7,
    thicknessMm: 8.8,
    weightG: 210,
    ingressProtection: "IP68",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      SNAPDRAGON_7S_GEN_3,
      12,
      256,
      {
        size: 6.7,
        width: 1220,
        height: 2712,
        refresh: 120,
        peakNits: 3000,
        technology: "amoled",
      },
      { capacityMah: 5110, wiredW: 120 },
      { cameraMegapixel: 200, storageStandard: "ufs31" },
    ),
  },
  {
    brandSlug: "xiaomi",
    categorySlug: "smartphone",
    familyName: "POCO F Series",
    familySlug: "poco-f6-pro-series",
    modelName: "POCO F6 Pro",
    modelSlug: "poco-f6-pro",
    announcementDate: "2024-05-23",
    releaseDate: "2024-05-23",
    generation: "F6 Pro",
    description:
      "Điện thoại thiên về hiệu năng với Snapdragon 8 Gen 2 và màn hình WQHD+.",
    variantName: "12GB/512GB Black",
    colorName: "Black",
    colorHex: "#262626",
    launchPrice: 499,
    heightMm: 160.9,
    widthMm: 75,
    thicknessMm: 8.2,
    weightG: 209,
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      SNAPDRAGON_8_GEN_2,
      12,
      512,
      {
        size: 6.7,
        width: 1440,
        height: 3200,
        refresh: 120,
        peakNits: 4000,
        technology: "amoled",
      },
      { capacityMah: 5000, wiredW: 120 },
    ),
  },
  {
    brandSlug: "xiaomi",
    categorySlug: "smartphone",
    familyName: "Xiaomi MIX Series",
    familySlug: "xiaomi-mix-flip-series",
    modelName: "Xiaomi MIX Flip",
    modelSlug: "xiaomi-mix-flip",
    announcementDate: "2024-07-19",
    releaseDate: "2024-07-19",
    generation: "MIX Flip",
    description: "Điện thoại gập vỏ sò có màn hình ngoài lớn và camera Leica.",
    variantName: "12GB/512GB Purple",
    colorName: "Purple",
    colorHex: "#C5B6D8",
    launchPrice: 1299,
    heightMm: 167.5,
    widthMm: 74,
    thicknessMm: 7.6,
    weightG: 192,
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      SNAPDRAGON_8_GEN_3,
      12,
      512,
      { size: 6.9, width: 1224, height: 2912, refresh: 120, peakNits: 3000 },
      { capacityMah: 4780, wiredW: 67, wirelessW: 50 },
    ),
  },
  {
    brandSlug: "oneplus",
    categorySlug: "smartphone",
    familyName: "OnePlus 12 Series",
    familySlug: "oneplus-12-series",
    modelName: "OnePlus 12",
    modelSlug: "oneplus-12",
    announcementDate: "2023-12-05",
    releaseDate: "2023-12-11",
    generation: "Gen 12",
    description:
      "Điện thoại cao cấp với Snapdragon 8 Gen 3, camera Hasselblad và sạc nhanh.",
    variantName: "16GB/512GB Flowy Emerald",
    colorName: "Flowy Emerald",
    colorHex: "#487B67",
    launchPrice: 899.99,
    heightMm: 164.3,
    widthMm: 75.8,
    thicknessMm: 9.2,
    weightG: 220,
    ingressProtection: "IP65",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      SNAPDRAGON_8_GEN_3,
      16,
      512,
      { size: 6.8, width: 1440, height: 3168, refresh: 120, peakNits: 4500 },
      { capacityMah: 5400, wiredW: 100, wirelessW: 50 },
    ),
  },
  {
    brandSlug: "oneplus",
    categorySlug: "smartphone",
    familyName: "OnePlus Nord Series",
    familySlug: "oneplus-nord-4-series",
    modelName: "OnePlus Nord 4",
    modelSlug: "oneplus-nord-4",
    announcementDate: "2024-07-16",
    releaseDate: "2024-08-08",
    generation: "Nord 4",
    description:
      "Điện thoại tầm trung thân kim loại nguyên khối, pin lớn và sạc 100 W.",
    variantName: "12GB/256GB Mercurial Silver",
    colorName: "Mercurial Silver",
    colorHex: "#B7B7B5",
    launchPrice: 499,
    heightMm: 162.6,
    widthMm: 75,
    thicknessMm: 8,
    weightG: 199.5,
    ingressProtection: "IP65",
    frameMaterial: "Nhôm",
    speakerCount: 2,
    module: phoneHardware(
      SNAPDRAGON_7_PLUS_GEN_3,
      12,
      256,
      {
        size: 6.7,
        width: 1240,
        height: 2772,
        refresh: 120,
        peakNits: 2150,
        technology: "amoled",
      },
      { capacityMah: 5500, wiredW: 100 },
    ),
  },
  {
    brandSlug: "oneplus",
    categorySlug: "smartphone",
    familyName: "OnePlus Open Series",
    familySlug: "oneplus-open-series",
    modelName: "OnePlus Open",
    modelSlug: "oneplus-open",
    announcementDate: "2023-10-19",
    releaseDate: "2023-10-26",
    generation: "Open",
    description:
      "Điện thoại gập dạng sách mỏng nhẹ với camera Hasselblad và đa nhiệm linh hoạt.",
    variantName: "16GB/512GB Emerald Dusk",
    colorName: "Emerald Dusk",
    colorHex: "#375649",
    launchPrice: 1699.99,
    heightMm: 153.4,
    widthMm: 143.1,
    thicknessMm: 5.8,
    weightG: 239,
    ingressProtection: "IPX4",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 3,
    module: phoneHardware(
      SNAPDRAGON_8_GEN_2,
      16,
      512,
      { size: 7.8, width: 2268, height: 2440, refresh: 120, peakNits: 2800 },
      { capacityMah: 4805, wiredW: 67 },
      { cameraMegapixel: 48 },
    ),
  },
  {
    brandSlug: "oppo",
    categorySlug: "smartphone",
    familyName: "OPPO Reno13 Series",
    familySlug: "oppo-reno13-pro-series",
    modelName: "OPPO Reno13 Pro",
    modelSlug: "oppo-reno13-pro",
    announcementDate: "2024-11-25",
    releaseDate: "2024-11-29",
    generation: "Reno13",
    description:
      "Điện thoại mỏng nhẹ với Dimensity 8350, camera chân dung và pin lớn.",
    variantName: "12GB/512GB Plume Purple",
    colorName: "Plume Purple",
    colorHex: "#CABAD8",
    launchPrice: 799,
    heightMm: 162.8,
    widthMm: 76.6,
    thicknessMm: 7.6,
    weightG: 195,
    ingressProtection: "IP68/IP69",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      DIMENSITY_8350,
      12,
      512,
      {
        size: 6.8,
        width: 1272,
        height: 2800,
        refresh: 120,
        peakNits: 1600,
        technology: "amoled",
      },
      { capacityMah: 5800, wiredW: 80 },
    ),
  },
  {
    brandSlug: "oppo",
    categorySlug: "smartphone",
    familyName: "OPPO Find N Series",
    familySlug: "oppo-find-n3-flip-series",
    modelName: "OPPO Find N3 Flip",
    modelSlug: "oppo-find-n3-flip",
    announcementDate: "2023-08-29",
    releaseDate: "2023-09-08",
    generation: "N3 Flip",
    description:
      "Điện thoại gập vỏ sò với camera Hasselblad và màn hình phụ dọc.",
    variantName: "12GB/256GB Cream Gold",
    colorName: "Cream Gold",
    colorHex: "#D8C7A9",
    launchPrice: 999,
    heightMm: 166.4,
    widthMm: 75.8,
    thicknessMm: 7.5,
    weightG: 198,
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      DIMENSITY_9200,
      12,
      256,
      {
        size: 6.8,
        width: 1080,
        height: 2520,
        refresh: 120,
        peakNits: 1600,
        technology: "amoled",
      },
      { capacityMah: 4300, wiredW: 44 },
    ),
  },
  {
    brandSlug: "vivo",
    categorySlug: "smartphone",
    familyName: "vivo X100 Series",
    familySlug: "vivo-x100-ultra-series",
    modelName: "vivo X100 Ultra",
    modelSlug: "vivo-x100-ultra",
    announcementDate: "2024-05-13",
    releaseDate: "2024-05-28",
    generation: "X100 Ultra",
    description:
      "Điện thoại nhiếp ảnh cao cấp với camera chụp xa 200 MP và ống kính ZEISS.",
    variantName: "16GB/512GB Titanium",
    colorName: "Titanium",
    colorHex: "#B5B2AA",
    launchPrice: 1099,
    heightMm: 164.1,
    widthMm: 75.6,
    thicknessMm: 9.2,
    weightG: 229,
    ingressProtection: "IP69",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      SNAPDRAGON_8_GEN_3,
      16,
      512,
      { size: 6.8, width: 1440, height: 3200, refresh: 120, peakNits: 3000 },
      { capacityMah: 5500, wiredW: 80, wirelessW: 30 },
      { cameraMegapixel: 50 },
    ),
  },
  {
    brandSlug: "vivo",
    categorySlug: "smartphone",
    familyName: "vivo V40 Series",
    familySlug: "vivo-v40-series",
    modelName: "vivo V40",
    modelSlug: "vivo-v40",
    announcementDate: "2024-06-17",
    releaseDate: "2024-07-03",
    generation: "V40",
    description:
      "Điện thoại mỏng với camera ZEISS, pin 5500 mAh và màn hình AMOLED sáng.",
    variantName: "12GB/256GB Nebula Purple",
    colorName: "Nebula Purple",
    colorHex: "#B9A4CF",
    launchPrice: 549,
    heightMm: 164.2,
    widthMm: 74.9,
    thicknessMm: 7.6,
    weightG: 190,
    ingressProtection: "IP68",
    frameMaterial: "Nhựa",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      SNAPDRAGON_7_GEN_3,
      12,
      256,
      {
        size: 6.8,
        width: 1260,
        height: 2800,
        refresh: 120,
        peakNits: 4500,
        technology: "amoled",
      },
      { capacityMah: 5500, wiredW: 80 },
      { storageStandard: "ufs31" },
    ),
  },
  {
    brandSlug: "sony",
    categorySlug: "smartphone",
    familyName: "Xperia 5 Series",
    familySlug: "sony-xperia-5-v-series",
    modelName: "Sony Xperia 5 V",
    modelSlug: "sony-xperia-5-v",
    announcementDate: "2023-09-01",
    releaseDate: "2023-09-25",
    generation: "Mark V",
    description:
      "Điện thoại Sony nhỏ gọn với màn hình OLED, camera Alpha và giắc tai nghe.",
    variantName: "8GB/128GB Blue",
    colorName: "Blue",
    colorHex: "#6D8293",
    launchPrice: 999,
    heightMm: 154,
    widthMm: 68,
    thicknessMm: 8.6,
    weightG: 182,
    ingressProtection: "IP65/IP68",
    frameMaterial: "Nhôm",
    backMaterial: "Gorilla Glass Victus 2",
    speakerCount: 2,
    headphoneJack: true,
    microSd: true,
    module: phoneHardware(
      SNAPDRAGON_8_GEN_2,
      8,
      128,
      { size: 6.1, width: 1080, height: 2520, refresh: 120, peakNits: 1000 },
      { capacityMah: 5000, wiredW: 30, wirelessW: 15 },
      { storageStandard: "ufs31", cameraMegapixel: 48 },
    ),
  },
  {
    brandSlug: "nothing",
    categorySlug: "smartphone",
    familyName: "Nothing Phone (2a) Series",
    familySlug: "nothing-phone-2a-series",
    modelName: "Nothing Phone (2a)",
    modelSlug: "nothing-phone-2a",
    announcementDate: "2024-03-05",
    releaseDate: "2024-03-12",
    generation: "Phone 2a",
    description:
      "Điện thoại tầm trung có thiết kế Glyph đặc trưng và giao diện Nothing OS.",
    variantName: "12GB/256GB Milk",
    colorName: "Milk",
    colorHex: "#E8E5DB",
    launchPrice: 349,
    heightMm: 161.7,
    widthMm: 76.3,
    thicknessMm: 8.6,
    weightG: 190,
    ingressProtection: "IP54",
    frameMaterial: "Nhựa tái chế",
    backMaterial: "Polycarbonate",
    speakerCount: 2,
    module: phoneHardware(
      DIMENSITY_7300,
      12,
      256,
      {
        size: 6.7,
        width: 1084,
        height: 2412,
        refresh: 120,
        peakNits: 1300,
        technology: "amoled",
      },
      { capacityMah: 5000, wiredW: 45 },
      { storageStandard: "ufs31" },
    ),
  },
  {
    brandSlug: "nothing",
    categorySlug: "smartphone",
    familyName: "Nothing Phone (3a) Series",
    familySlug: "nothing-phone-3a-pro-series",
    modelName: "Nothing Phone (3a) Pro",
    modelSlug: "nothing-phone-3a-pro",
    announcementDate: "2025-03-04",
    releaseDate: "2025-03-11",
    generation: "Phone 3a Pro",
    description:
      "Điện thoại tầm trung có camera chụp xa tiềm vọng, Glyph và pin 5000 mAh.",
    variantName: "12GB/256GB Grey",
    colorName: "Grey",
    colorHex: "#9B9A96",
    launchPrice: 459,
    heightMm: 163.5,
    widthMm: 77.5,
    thicknessMm: 8.4,
    weightG: 211,
    ingressProtection: "IP64",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      SNAPDRAGON_7S_GEN_3,
      12,
      256,
      {
        size: 6.8,
        width: 1080,
        height: 2392,
        refresh: 120,
        peakNits: 3000,
        technology: "amoled",
      },
      { capacityMah: 5000, wiredW: 50 },
      { storageStandard: "ufs31" },
    ),
  },
  {
    brandSlug: "huawei",
    categorySlug: "smartphone",
    familyName: "Huawei Mate 70 Series",
    familySlug: "huawei-mate-70-pro-series",
    modelName: "Huawei Mate 70 Pro",
    modelSlug: "huawei-mate-70-pro",
    announcementDate: "2024-11-26",
    releaseDate: "2024-12-04",
    generation: "Mate 70",
    description:
      "Điện thoại cao cấp với camera XMAGE, liên lạc vệ tinh và HarmonyOS.",
    variantName: "12GB/512GB Spruce Green",
    colorName: "Spruce Green",
    colorHex: "#4B6B5A",
    launchPrice: 1099,
    heightMm: 164.6,
    widthMm: 79.5,
    thicknessMm: 8.2,
    weightG: 221,
    ingressProtection: "IP68/IP69",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      KIRIN_9020,
      12,
      512,
      { size: 6.9, width: 1212, height: 2616, refresh: 120, peakNits: 2500 },
      { capacityMah: 5500, wiredW: 100, wirelessW: 80 },
      { operatingSystem: "harmonyOs42" },
    ),
  },
  {
    brandSlug: "huawei",
    categorySlug: "smartphone",
    familyName: "Huawei Pura 70 Series",
    familySlug: "huawei-pura-70-pro-series",
    modelName: "Huawei Pura 70 Pro",
    modelSlug: "huawei-pura-70-pro",
    announcementDate: "2024-04-18",
    releaseDate: "2024-04-22",
    generation: "Pura 70",
    description:
      "Điện thoại nhiếp ảnh với camera XMAGE, màn hình LTPO và sạc không dây nhanh.",
    variantName: "12GB/512GB White",
    colorName: "White",
    colorHex: "#E7E5DF",
    launchPrice: 999,
    heightMm: 162.6,
    widthMm: 75.1,
    thicknessMm: 8.4,
    weightG: 220,
    ingressProtection: "IP68",
    frameMaterial: "Nhôm",
    backMaterial: "Kính",
    speakerCount: 2,
    module: phoneHardware(
      KIRIN_9010,
      12,
      512,
      { size: 6.8, width: 1260, height: 2844, refresh: 120, peakNits: 2500 },
      { capacityMah: 5050, wiredW: 100, wirelessW: 80 },
      { operatingSystem: "harmonyOs42" },
    ),
  },

  // 15 máy tính xách tay
  {
    brandSlug: "apple",
    categorySlug: "laptop",
    familyName: "MacBook Air M4 Series",
    familySlug: "macbook-air-15-m4-series",
    modelName: "MacBook Air 15-inch M4",
    modelSlug: "macbook-air-15-m4",
    announcementDate: "2025-03-05",
    releaseDate: "2025-03-12",
    generation: "M4",
    description:
      "Máy tính xách tay màn hình lớn, không quạt với chip M4 và thân nhôm mỏng nhẹ.",
    variantName: "16GB/256GB Sky Blue",
    colorName: "Sky Blue",
    colorHex: "#A8B6C1",
    launchPrice: 1199,
    heightMm: 237.6,
    widthMm: 340.4,
    thicknessMm: 11.5,
    weightG: 1510,
    frameMaterial: "Nhôm tái chế",
    speakerCount: 6,
    audioTuning: "Spatial Audio",
    module: laptopHardware(
      APPLE_M4,
      16,
      256,
      {
        size: 15.3,
        width: 2880,
        height: 1864,
        refresh: 60,
        peakNits: 500,
        technology: "ips-lcd",
      },
      66.5,
      {
        operatingSystem: "macOs15",
        memoryStandard: "unified",
        storageStandard: "apple-nvme",
        ports: [{ standard: "thunderbolt", count: 2 }],
      },
    ),
  },
  {
    brandSlug: "apple",
    categorySlug: "laptop",
    familyName: "MacBook Pro M4 Series",
    familySlug: "macbook-pro-16-m4-max-series",
    modelName: "MacBook Pro 16-inch M4 Max",
    modelSlug: "macbook-pro-16-m4-max",
    announcementDate: "2024-10-30",
    releaseDate: "2024-11-08",
    generation: "M4 Max",
    description:
      "Máy trạm di động Apple với M4 Max, màn hình Mini LED và pin dung lượng lớn.",
    variantName: "48GB/1TB Space Black",
    colorName: "Space Black",
    colorHex: "#2E2F30",
    launchPrice: 3999,
    heightMm: 248.1,
    widthMm: 355.7,
    thicknessMm: 16.8,
    weightG: 2150,
    frameMaterial: "Nhôm tái chế",
    speakerCount: 6,
    audioTuning: "Spatial Audio",
    module: laptopHardware(
      APPLE_M4_MAX,
      48,
      1024,
      {
        size: 16.2,
        width: 3456,
        height: 2234,
        refresh: 120,
        peakNits: 1600,
        technology: "mini-led",
      },
      100,
      {
        operatingSystem: "macOs15",
        memoryStandard: "unified",
        storageStandard: "apple-nvme",
        ports: [
          { standard: "thunderbolt", count: 3 },
          { standard: "hdmi21", count: 1 },
        ],
      },
    ),
  },
  {
    brandSlug: "dell",
    categorySlug: "laptop",
    familyName: "Dell XPS 14 Series",
    familySlug: "dell-xps-14-9440-series",
    modelName: "Dell XPS 14 9440",
    modelSlug: "dell-xps-14-9440",
    announcementDate: "2024-01-04",
    releaseDate: "2024-02-20",
    generation: "9440",
    description:
      "Máy tính xách tay cao cấp 14,5 inch với thân nhôm CNC và màn hình OLED.",
    variantName: "32GB/1TB Graphite",
    colorName: "Graphite",
    colorHex: "#4A4A4A",
    launchPrice: 1999,
    heightMm: 215,
    widthMm: 320,
    thicknessMm: 18.7,
    weightG: 1680,
    frameMaterial: "Nhôm CNC",
    speakerCount: 4,
    audioTuning: "Waves MaxxAudio",
    module: laptopHardware(
      CORE_ULTRA_7_155H,
      32,
      1024,
      {
        size: 14.5,
        width: 3200,
        height: 2000,
        refresh: 120,
        peakNits: 500,
      },
      69.5,
    ),
  },
  {
    brandSlug: "dell",
    categorySlug: "laptop",
    familyName: "Alienware m Series",
    familySlug: "alienware-m16-r2-series",
    modelName: "Alienware m16 R2",
    modelSlug: "alienware-m16-r2",
    announcementDate: "2024-01-11",
    releaseDate: "2024-02-01",
    generation: "R2",
    description:
      "Máy tính chơi game 16 inch với RTX 4070, bàn phím RGB và hệ thống tản nhiệt lớn.",
    variantName: "32GB/1TB Dark Metallic Moon",
    colorName: "Dark Metallic Moon",
    colorHex: "#31343A",
    launchPrice: 2099,
    heightMm: 249.4,
    widthMm: 363.9,
    thicknessMm: 23.5,
    weightG: 2610,
    frameMaterial: "Nhôm và magiê",
    speakerCount: 2,
    module: laptopHardware(
      CORE_ULTRA_9_185H_RTX4070,
      32,
      1024,
      {
        size: 16,
        width: 2560,
        height: 1600,
        refresh: 240,
        peakNits: 300,
        technology: "ips-lcd",
      },
      90,
    ),
  },
  {
    brandSlug: "asus",
    categorySlug: "laptop",
    familyName: "ASUS Zenbook S Series",
    familySlug: "asus-zenbook-s-14-ux5406-series",
    modelName: "ASUS Zenbook S 14 UX5406",
    modelSlug: "asus-zenbook-s-14-ux5406",
    announcementDate: "2024-09-04",
    releaseDate: "2024-09-24",
    generation: "UX5406",
    description:
      "Máy tính xách tay siêu mỏng với Core Ultra 200V và màn hình OLED 3K.",
    variantName: "32GB/1TB Zumaia Gray",
    colorName: "Zumaia Gray",
    colorHex: "#676765",
    launchPrice: 1499,
    heightMm: 214.7,
    widthMm: 310.3,
    thicknessMm: 12.9,
    weightG: 1200,
    frameMaterial: "Ceraluminum",
    speakerCount: 4,
    audioTuning: "Harman Kardon",
    module: laptopHardware(
      CORE_ULTRA_7_258V,
      32,
      1024,
      {
        size: 14,
        width: 2880,
        height: 1800,
        refresh: 120,
        peakNits: 500,
      },
      72,
    ),
  },
  {
    brandSlug: "asus",
    categorySlug: "laptop",
    familyName: "ROG Strix SCAR Series",
    familySlug: "asus-rog-strix-scar-16-2025-series",
    modelName: "ROG Strix SCAR 16 (2025)",
    modelSlug: "asus-rog-strix-scar-16-2025",
    announcementDate: "2025-01-06",
    releaseDate: "2025-02-15",
    generation: "G635",
    description:
      "Máy tính chơi game hiệu năng rất cao với RTX 5080 và màn hình Mini LED 240 Hz.",
    variantName: "32GB/2TB Off Black",
    colorName: "Off Black",
    colorHex: "#202124",
    launchPrice: 3299,
    heightMm: 268,
    widthMm: 354,
    thicknessMm: 30.8,
    weightG: 2850,
    frameMaterial: "Nhôm và polycarbonate",
    speakerCount: 4,
    audioTuning: "Dolby Atmos",
    module: laptopHardware(
      CORE_ULTRA_9_285HX_RTX5080,
      32,
      2048,
      {
        size: 16,
        width: 2560,
        height: 1600,
        refresh: 240,
        peakNits: 1200,
        technology: "mini-led",
      },
      90,
    ),
  },
  {
    brandSlug: "lenovo",
    categorySlug: "laptop",
    familyName: "Lenovo Yoga Slim Series",
    familySlug: "lenovo-yoga-slim-7x-series",
    modelName: "Lenovo Yoga Slim 7x",
    modelSlug: "lenovo-yoga-slim-7x",
    announcementDate: "2024-05-20",
    releaseDate: "2024-06-18",
    generation: "14Q8X9",
    description:
      "Máy tính Copilot+ mỏng nhẹ với Snapdragon X Elite và màn hình OLED cảm ứng.",
    variantName: "32GB/1TB Cosmic Blue",
    colorName: "Cosmic Blue",
    colorHex: "#273B5A",
    launchPrice: 1199,
    heightMm: 203.5,
    widthMm: 325,
    thicknessMm: 12.9,
    weightG: 1280,
    frameMaterial: "Nhôm",
    speakerCount: 4,
    audioTuning: "Dolby Atmos",
    module: laptopHardware(
      SNAPDRAGON_X_ELITE,
      32,
      1024,
      {
        size: 14.5,
        width: 2944,
        height: 1840,
        refresh: 90,
        peakNits: 1000,
      },
      70,
    ),
  },
  {
    brandSlug: "lenovo",
    categorySlug: "laptop",
    familyName: "Lenovo Legion Pro Series",
    familySlug: "lenovo-legion-pro-7i-gen-10-series",
    modelName: "Lenovo Legion Pro 7i Gen 10",
    modelSlug: "lenovo-legion-pro-7i-gen-10",
    announcementDate: "2025-01-07",
    releaseDate: "2025-03-15",
    generation: "Gen 10",
    description:
      "Máy tính chơi game 16 inch với RTX 5080, màn hình OLED và tản nhiệt hiệu suất cao.",
    variantName: "32GB/2TB Eclipse Black",
    colorName: "Eclipse Black",
    colorHex: "#181A1C",
    launchPrice: 2999,
    heightMm: 262,
    widthMm: 364,
    thicknessMm: 26.6,
    weightG: 2700,
    frameMaterial: "Nhôm",
    speakerCount: 2,
    audioTuning: "Nahimic",
    module: laptopHardware(
      CORE_ULTRA_9_285HX_RTX5080,
      32,
      2048,
      {
        size: 16,
        width: 2560,
        height: 1600,
        refresh: 240,
        peakNits: 500,
      },
      99.9,
    ),
  },
  {
    brandSlug: "microsoft",
    categorySlug: "laptop",
    familyName: "Surface Laptop Series",
    familySlug: "surface-laptop-7-15-series",
    modelName: "Surface Laptop 7 15-inch",
    modelSlug: "surface-laptop-7-15",
    announcementDate: "2024-05-20",
    releaseDate: "2024-06-18",
    generation: "7th Edition",
    description:
      "Máy tính Copilot+ màn hình cảm ứng 15 inch với Snapdragon X Elite và pin lâu.",
    variantName: "16GB/512GB Platinum",
    colorName: "Platinum",
    colorHex: "#D4D4D1",
    launchPrice: 1299,
    heightMm: 239,
    widthMm: 329,
    thicknessMm: 18.3,
    weightG: 1660,
    frameMaterial: "Nhôm anod hóa",
    speakerCount: 2,
    audioTuning: "Dolby Atmos",
    module: laptopHardware(
      SNAPDRAGON_X_ELITE,
      16,
      512,
      {
        size: 15,
        width: 2496,
        height: 1664,
        refresh: 120,
        peakNits: 600,
        technology: "ips-lcd",
      },
      66,
    ),
  },
  {
    brandSlug: "acer",
    categorySlug: "laptop",
    familyName: "Acer Swift AI Series",
    familySlug: "acer-swift-14-ai-sf14-51-series",
    modelName: "Acer Swift 14 AI SF14-51",
    modelSlug: "acer-swift-14-ai-sf14-51",
    announcementDate: "2024-09-04",
    releaseDate: "2024-10-15",
    generation: "SF14-51",
    description:
      "Máy tính AI mỏng nhẹ với Core Ultra 200V, màn hình OLED và pin 65 Wh.",
    variantName: "32GB/1TB Steam Blue",
    colorName: "Steam Blue",
    colorHex: "#5A6C7A",
    launchPrice: 1199,
    heightMm: 227,
    widthMm: 312,
    thicknessMm: 15.9,
    weightG: 1260,
    frameMaterial: "Nhôm",
    speakerCount: 2,
    module: laptopHardware(
      CORE_ULTRA_7_258V,
      32,
      1024,
      {
        size: 14,
        width: 2880,
        height: 1800,
        refresh: 90,
        peakNits: 500,
      },
      65,
    ),
  },
  {
    brandSlug: "hp",
    categorySlug: "laptop",
    familyName: "HP Spectre x360 Series",
    familySlug: "hp-spectre-x360-14-2024-series",
    modelName: "HP Spectre x360 14 (2024)",
    modelSlug: "hp-spectre-x360-14-2024",
    announcementDate: "2024-01-08",
    releaseDate: "2024-01-15",
    generation: "14-eu",
    description:
      "Máy tính hai trong một cao cấp với màn hình OLED, bút cảm ứng và camera 9 MP.",
    variantName: "32GB/1TB Slate Blue",
    colorName: "Slate Blue",
    colorHex: "#45586C",
    launchPrice: 1499,
    heightMm: 220,
    widthMm: 313.7,
    thicknessMm: 16.9,
    weightG: 1440,
    frameMaterial: "Nhôm tái chế",
    speakerCount: 4,
    audioTuning: "Poly Studio",
    module: laptopHardware(
      CORE_ULTRA_7_155H,
      32,
      1024,
      {
        size: 14,
        width: 2880,
        height: 1800,
        refresh: 120,
        peakNits: 500,
      },
      68,
    ),
  },
  {
    brandSlug: "msi",
    categorySlug: "laptop",
    familyName: "MSI Stealth Series",
    familySlug: "msi-stealth-a16-ai-plus-series",
    modelName: "MSI Stealth A16 AI+",
    modelSlug: "msi-stealth-a16-ai-plus",
    announcementDate: "2024-06-03",
    releaseDate: "2024-09-01",
    generation: "A3XV",
    description: "Máy tính chơi game mỏng 16 inch với Ryzen AI 9 và RTX 4070.",
    variantName: "32GB/1TB Core Black",
    colorName: "Core Black",
    colorHex: "#202224",
    launchPrice: 2299,
    heightMm: 259.5,
    widthMm: 355.8,
    thicknessMm: 19.9,
    weightG: 2100,
    frameMaterial: "Hợp kim magiê nhôm",
    speakerCount: 6,
    audioTuning: "Dynaudio",
    module: laptopHardware(
      RYZEN_AI_9_HX370_RTX4070,
      32,
      1024,
      {
        size: 16,
        width: 2560,
        height: 1600,
        refresh: 240,
        peakNits: 500,
        technology: "ips-lcd",
      },
      99.9,
    ),
  },
  {
    brandSlug: "razer",
    categorySlug: "laptop",
    familyName: "Razer Blade Series",
    familySlug: "razer-blade-14-2024-series",
    modelName: "Razer Blade 14 (2024)",
    modelSlug: "razer-blade-14-2024",
    announcementDate: "2024-01-08",
    releaseDate: "2024-01-23",
    generation: "RZ09-0508",
    description:
      "Máy tính chơi game 14 inch thân nhôm CNC với Ryzen 7 và RTX 4060.",
    variantName: "16GB/1TB Mercury",
    colorName: "Mercury",
    colorHex: "#C5C5C1",
    launchPrice: 2199,
    heightMm: 228,
    widthMm: 310.7,
    thicknessMm: 17.9,
    weightG: 1840,
    frameMaterial: "Nhôm CNC",
    speakerCount: 2,
    audioTuning: "THX Spatial Audio",
    module: laptopHardware(
      RYZEN_7_8845HS_RTX4060,
      16,
      1024,
      {
        size: 14,
        width: 2560,
        height: 1600,
        refresh: 240,
        peakNits: 500,
        technology: "ips-lcd",
      },
      68.1,
    ),
  },
  {
    brandSlug: "samsung",
    categorySlug: "laptop",
    familyName: "Galaxy Book4 Series",
    familySlug: "samsung-galaxy-book4-ultra-series",
    modelName: "Samsung Galaxy Book4 Ultra",
    modelSlug: "samsung-galaxy-book4-ultra",
    announcementDate: "2023-12-15",
    releaseDate: "2024-02-26",
    generation: "Book4 Ultra",
    description:
      "Máy tính sáng tạo 16 inch với màn hình AMOLED cảm ứng và GPU RTX 4070.",
    variantName: "32GB/1TB Moonstone Gray",
    colorName: "Moonstone Gray",
    colorHex: "#6B6C6D",
    launchPrice: 2999,
    heightMm: 250.4,
    widthMm: 355.4,
    thicknessMm: 16.5,
    weightG: 1860,
    frameMaterial: "Nhôm",
    speakerCount: 4,
    audioTuning: "AKG",
    module: laptopHardware(
      CORE_ULTRA_9_185H_RTX4070,
      32,
      1024,
      {
        size: 16,
        width: 2880,
        height: 1800,
        refresh: 120,
        peakNits: 500,
        technology: "amoled",
      },
      76,
    ),
  },
  {
    brandSlug: "framework",
    categorySlug: "laptop",
    familyName: "Framework Laptop 13 Series",
    familySlug: "framework-laptop-13-amd-2025-series",
    modelName: "Framework Laptop 13 (AMD Ryzen AI 300)",
    modelSlug: "framework-laptop-13-amd-2025",
    announcementDate: "2025-02-25",
    releaseDate: "2025-04-01",
    generation: "2025",
    description:
      "Máy tính mô-đun dễ sửa chữa với cổng mở rộng và nền tảng Ryzen AI 300.",
    variantName: "32GB/1TB Gray",
    colorName: "Gray",
    colorHex: "#777978",
    launchPrice: 1399,
    heightMm: 229,
    widthMm: 297,
    thicknessMm: 15.9,
    weightG: 1300,
    frameMaterial: "Nhôm tái chế",
    speakerCount: 2,
    module: laptopHardware(
      RYZEN_AI_9_HX370,
      32,
      1024,
      {
        size: 13.5,
        width: 2880,
        height: 1920,
        refresh: 120,
        peakNits: 500,
        technology: "ips-lcd",
      },
      61,
      {
        ports: [{ standard: "usb4", count: 4 }],
      },
    ),
  },

  // 5 máy tính bảng
  {
    brandSlug: "apple",
    categorySlug: "tablet",
    familyName: "iPad Air M2 Series",
    familySlug: "ipad-air-13-m2-series",
    modelName: "iPad Air 13-inch (M2)",
    modelSlug: "ipad-air-13-m2",
    announcementDate: "2024-05-07",
    releaseDate: "2024-05-15",
    generation: "M2",
    description:
      "Máy tính bảng màn hình lớn với chip M2, hỗ trợ Apple Pencil Pro và Magic Keyboard.",
    variantName: "8GB/128GB Wi-Fi Blue",
    colorName: "Blue",
    colorHex: "#A6B6C8",
    launchPrice: 799,
    heightMm: 214.9,
    widthMm: 280.6,
    thicknessMm: 6.1,
    weightG: 617,
    frameMaterial: "Nhôm tái chế",
    speakerCount: 2,
    module: tabletHardware(
      APPLE_M2,
      8,
      128,
      {
        size: 13,
        width: 2732,
        height: 2048,
        refresh: 60,
        peakNits: 600,
        technology: "ips-lcd",
      },
      { capacityMah: 9705, wiredW: 30 },
      {
        operatingSystem: "ipadOs18",
        memoryStandard: "unified",
        storageStandard: "apple-nvme",
      },
    ),
  },
  {
    brandSlug: "samsung",
    categorySlug: "tablet",
    familyName: "Galaxy Tab S9 FE Series",
    familySlug: "galaxy-tab-s9-fe-series",
    modelName: "Samsung Galaxy Tab S9 FE",
    modelSlug: "galaxy-tab-s9-fe",
    announcementDate: "2023-10-04",
    releaseDate: "2023-10-16",
    generation: "Tab S9 FE",
    description:
      "Máy tính bảng chống nước đi kèm S Pen, phù hợp học tập và ghi chú.",
    variantName: "8GB/256GB Wi-Fi Mint",
    colorName: "Mint",
    colorHex: "#C9DACE",
    launchPrice: 519,
    heightMm: 165.8,
    widthMm: 254.3,
    thicknessMm: 6.5,
    weightG: 523,
    ingressProtection: "IP68",
    frameMaterial: "Nhôm",
    speakerCount: 2,
    microSd: true,
    module: tabletHardware(
      EXYNOS_1380,
      8,
      256,
      {
        size: 10.9,
        width: 1440,
        height: 2304,
        refresh: 90,
        peakNits: 600,
        technology: "ips-lcd",
      },
      { capacityMah: 8000, wiredW: 45 },
      { operatingSystem: "android14", storageStandard: "ufs31" },
    ),
  },
  {
    brandSlug: "xiaomi",
    categorySlug: "tablet",
    familyName: "Xiaomi Pad 7 Series",
    familySlug: "xiaomi-pad-7-pro-series",
    modelName: "Xiaomi Pad 7 Pro",
    modelSlug: "xiaomi-pad-7-pro",
    announcementDate: "2024-10-29",
    releaseDate: "2024-10-31",
    generation: "Pad 7 Pro",
    description:
      "Máy tính bảng 11,2 inch 144 Hz với Snapdragon 8s Gen 3 và sạc 67 W.",
    variantName: "12GB/512GB Gray",
    colorName: "Gray",
    colorHex: "#777A7D",
    launchPrice: 499,
    heightMm: 173.4,
    widthMm: 251.2,
    thicknessMm: 6.2,
    weightG: 500,
    frameMaterial: "Nhôm",
    speakerCount: 4,
    audioTuning: "Dolby Atmos",
    module: tabletHardware(
      SNAPDRAGON_8S_GEN_3,
      12,
      512,
      {
        size: 11.2,
        width: 2136,
        height: 3200,
        refresh: 144,
        peakNits: 800,
        technology: "ips-lcd",
      },
      { capacityMah: 8850, wiredW: 67 },
    ),
  },
  {
    brandSlug: "oneplus",
    categorySlug: "tablet",
    familyName: "OnePlus Pad Series",
    familySlug: "oneplus-pad-original-series",
    modelName: "OnePlus Pad",
    modelSlug: "oneplus-pad",
    announcementDate: "2023-02-07",
    releaseDate: "2023-04-28",
    generation: "Pad 1",
    description:
      "Máy tính bảng tỷ lệ 7:5 với màn hình 144 Hz và chip Dimensity 9000.",
    variantName: "8GB/128GB Halo Green",
    colorName: "Halo Green",
    colorHex: "#4C665C",
    launchPrice: 479,
    heightMm: 189.4,
    widthMm: 258,
    thicknessMm: 6.5,
    weightG: 552,
    frameMaterial: "Nhôm",
    speakerCount: 4,
    audioTuning: "Dolby Atmos",
    module: tabletHardware(
      DIMENSITY_9000,
      8,
      128,
      {
        size: 11.6,
        width: 2000,
        height: 2800,
        refresh: 144,
        peakNits: 500,
        technology: "ips-lcd",
      },
      { capacityMah: 9510, wiredW: 67 },
      { operatingSystem: "android14", storageStandard: "ufs31" },
    ),
  },
  {
    brandSlug: "lenovo",
    categorySlug: "tablet",
    familyName: "Lenovo Tab Extreme Series",
    familySlug: "lenovo-tab-extreme-series",
    modelName: "Lenovo Tab Extreme",
    modelSlug: "lenovo-tab-extreme",
    announcementDate: "2023-01-05",
    releaseDate: "2023-06-01",
    generation: "TB570FU",
    description:
      "Máy tính bảng OLED 14,5 inch cho đa nhiệm, giải trí và làm việc với bàn phím rời.",
    variantName: "12GB/256GB Storm Gray",
    colorName: "Storm Gray",
    colorHex: "#5B5D60",
    launchPrice: 949,
    heightMm: 210.9,
    widthMm: 327.8,
    thicknessMm: 5.9,
    weightG: 740,
    frameMaterial: "Nhôm",
    speakerCount: 8,
    audioTuning: "JBL Dolby Atmos",
    microSd: true,
    module: tabletHardware(
      DIMENSITY_9000,
      12,
      256,
      {
        size: 14.5,
        width: 1876,
        height: 3000,
        refresh: 120,
        peakNits: 500,
      },
      { capacityMah: 12300, wiredW: 68 },
      { operatingSystem: "android14", storageStandard: "ufs31" },
    ),
  },
];

export const ADDITIONAL_CATALOG_ORGANIZATIONS = [
  {
    name: "Acer Incorporated",
    slug: "acer",
    shortName: "Acer",
    countryCode: "TW",
    websiteUrl: "https://www.acer.com",
  },
  {
    name: "HP Inc.",
    slug: "hp",
    shortName: "HP",
    countryCode: "US",
    websiteUrl: "https://www.hp.com",
  },
  {
    name: "Micro-Star International",
    slug: "msi",
    shortName: "MSI",
    countryCode: "TW",
    websiteUrl: "https://www.msi.com",
  },
  {
    name: "Razer Inc.",
    slug: "razer",
    shortName: "Razer",
    countryCode: "US",
    websiteUrl: "https://www.razer.com",
  },
  {
    name: "Framework Computer Inc.",
    slug: "framework",
    shortName: "Framework",
    countryCode: "US",
    websiteUrl: "https://frame.work",
  },
] as const;

export const ADDITIONAL_CATALOG_DEVICES: AdditionalCatalogDeviceSeed[] =
  EXPANSION.map(({ module: _module, ...device }) => device);

export const ADDITIONAL_CATALOG_MODULES: CatalogModuleSeed[] = EXPANSION.map(
  ({ modelSlug, modelName, module }) => ({
    modelSlug,
    ...module,
    display: {
      ...module.display,
      name: `${modelName} Display`,
      slug: `${modelSlug}-display`,
    },
  }),
);

if (
  ADDITIONAL_CATALOG_DEVICES.length !== 50 ||
  ADDITIONAL_CATALOG_MODULES.length !== 50
) {
  throw new Error(
    `Catalog expansion must contain exactly 50 devices and module profiles; found ${ADDITIONAL_CATALOG_DEVICES.length}/${ADDITIONAL_CATALOG_MODULES.length}.`,
  );
}
