export const EXTENDED_CATALOG_OPERATING_SYSTEMS = {
  ios18: {
    slug: "ios",
    name: "iOS",
    family: "iOS",
    kernel: "XNU",
    vendorSlug: "apple",
    version: "18.0",
    releaseDate: "2024-09-16",
  },
  android15: {
    slug: "android",
    name: "Android",
    family: "Android",
    kernel: "Linux",
    vendorSlug: "google",
    version: "15",
    releaseDate: "2024-09-03",
  },
  android14: {
    slug: "android",
    name: "Android",
    family: "Android",
    kernel: "Linux",
    vendorSlug: "google",
    version: "14",
    releaseDate: "2023-10-04",
  },
  android13: {
    slug: "android",
    name: "Android",
    family: "Android",
    kernel: "Linux",
    vendorSlug: "google",
    version: "13",
    releaseDate: "2022-08-15",
  },
  android12: {
    slug: "android",
    name: "Android",
    family: "Android",
    kernel: "Linux",
    vendorSlug: "google",
    version: "12",
    releaseDate: "2021-10-04",
  },
  android11: {
    slug: "android",
    name: "Android",
    family: "Android",
    kernel: "Linux",
    vendorSlug: "google",
    version: "11",
    releaseDate: "2020-09-08",
  },
  android10: {
    slug: "android",
    name: "Android",
    family: "Android",
    kernel: "Linux",
    vendorSlug: "google",
    version: "10",
    releaseDate: "2019-09-03",
  },
  android9: {
    slug: "android",
    name: "Android",
    family: "Android",
    kernel: "Linux",
    vendorSlug: "google",
    version: "9",
    releaseDate: "2018-08-06",
  },
  android8: {
    slug: "android",
    name: "Android",
    family: "Android",
    kernel: "Linux",
    vendorSlug: "google",
    version: "8.0",
    releaseDate: "2017-08-21",
  },
  android7: {
    slug: "android",
    name: "Android",
    family: "Android",
    kernel: "Linux",
    vendorSlug: "google",
    version: "7.0",
    releaseDate: "2016-08-22",
  },
  harmonyOs42: {
    slug: "harmonyos",
    name: "HarmonyOS",
    family: "HarmonyOS",
    kernel: "HarmonyOS",
    vendorSlug: "huawei",
    version: "4.2",
    releaseDate: "2024-04-11",
  },
  ipadOs18: {
    slug: "ipados",
    name: "iPadOS",
    family: "iPadOS",
    kernel: "XNU",
    vendorSlug: "apple",
    version: "18.0",
    releaseDate: "2024-09-16",
  },
  windows11: {
    slug: "windows-11",
    name: "Windows 11",
    family: "Windows",
    kernel: "Windows NT",
    vendorSlug: "microsoft",
    version: "24H2",
    releaseDate: "2024-10-01",
  },
  macOs15: {
    slug: "macos",
    name: "macOS",
    family: "macOS",
    kernel: "XNU",
    vendorSlug: "apple",
    version: "15.1",
    releaseDate: "2024-10-28",
  },
  watchOs11: {
    slug: "watchos",
    name: "watchOS",
    family: "watchOS",
    kernel: "XNU",
    vendorSlug: "apple",
    version: "11.0",
    releaseDate: "2024-09-16",
  },
  garminOs: {
    slug: "garmin-os",
    name: "Garmin OS",
    family: "Garmin wearable",
    kernel: "Embedded",
    vendorSlug: "garmin",
    version: "12.35",
    releaseDate: "2024-08-27",
  },
  wearOs5: {
    slug: "wear-os",
    name: "Wear OS",
    family: "Wear OS",
    kernel: "Linux",
    vendorSlug: "google",
    version: "5.0",
    releaseDate: "2024-07-10",
  },
  samsungEarbuds: {
    slug: "samsung-earbuds-firmware",
    name: "Samsung Earbuds Firmware",
    family: "Embedded audio",
    kernel: "Embedded",
    vendorSlug: "samsung",
    version: "R630XXU0AXJ1",
    releaseDate: "2024-10-01",
  },
  sonyEarbuds: {
    slug: "sony-earbuds-firmware",
    name: "Sony Earbuds Firmware",
    family: "Embedded audio",
    kernel: "Embedded",
    vendorSlug: "sony",
    version: "4.0.2",
    releaseDate: "2024-10-01",
  },
  boseEarbuds: {
    slug: "bose-earbuds-firmware",
    name: "Bose Earbuds Firmware",
    family: "Embedded audio",
    kernel: "Embedded",
    vendorSlug: "bose",
    version: "4.0.20",
    releaseDate: "2024-10-01",
  },
  appleAudio: {
    slug: "apple-audio-firmware",
    name: "Apple Audio Firmware",
    family: "Embedded audio",
    kernel: "Embedded",
    vendorSlug: "apple",
    version: "7B21",
    releaseDate: "2024-11-01",
  },
  nothingAudio: {
    slug: "nothing-audio-firmware",
    name: "Nothing Audio Firmware",
    family: "Embedded audio",
    kernel: "Embedded",
    vendorSlug: "nothing",
    version: "1.0.1.46",
    releaseDate: "2024-09-01",
  },
  webOs24: {
    slug: "webos-24",
    name: "webOS",
    family: "webOS",
    kernel: "Linux",
    vendorSlug: "lg",
    version: "24",
    releaseDate: "2024-03-01",
  },
  googleTv: {
    slug: "google-tv",
    name: "Google TV",
    family: "Android TV",
    kernel: "Linux",
    vendorSlug: "google",
    version: "12",
    releaseDate: "2024-05-01",
  },
  tizen8: {
    slug: "tizen-8-tv",
    name: "Tizen OS",
    family: "Tizen TV",
    kernel: "Linux",
    vendorSlug: "samsung",
    version: "8.0",
    releaseDate: "2024-01-01",
  },
  switchOs: {
    slug: "nintendo-switch-system-software",
    name: "Nintendo Switch System Software",
    family: "Nintendo",
    kernel: "Horizon",
    vendorSlug: "nintendo",
    version: "19.0",
    releaseDate: "2024-10-08",
  },
  steamOs: {
    slug: "steamos",
    name: "SteamOS",
    family: "Linux",
    kernel: "Linux",
    vendorSlug: "valve",
    version: "3.6",
    releaseDate: "2024-10-23",
  },
  kindleOs: {
    slug: "kindle-os",
    name: "Kindle OS",
    family: "Kindle",
    kernel: "Linux",
    vendorSlug: "amazon-devices",
    version: "5.17",
    releaseDate: "2024-10-16",
  },
  koboOs: {
    slug: "kobo-os",
    name: "Kobo OS",
    family: "Kobo",
    kernel: "Linux",
    vendorSlug: "kobo",
    version: "4.41",
    releaseDate: "2024-04-10",
  },
  booxAndroid: {
    slug: "boox-android",
    name: "BOOX Android",
    family: "Android",
    kernel: "Linux",
    vendorSlug: "boox",
    version: "12",
    releaseDate: "2021-10-04",
  },
} as const;

type OperatingSystemKey = keyof typeof EXTENDED_CATALOG_OPERATING_SYSTEMS;
type MemoryKey =
  | "lpddr5x"
  | "lpddr5"
  | "lpddr4x"
  | "unified"
  | "ddr5"
  | "embedded";
type StorageKey = "ufs4" | "ufs31" | "ufs21" | "apple-nvme" | "nvme" | "emmc";
type DisplayTechnologyKey =
  | "ltpo-oled"
  | "amoled"
  | "oled"
  | "ips-lcd"
  | "mini-led"
  | "e-ink";
type WirelessKey =
  | "wifi7"
  | "wifi6e"
  | "wifi5"
  | "bluetooth54"
  | "bluetooth53"
  | "bluetooth50"
  | "cellular5g"
  | "cellular4g";
type PortKey = "usb-c" | "usb-c-2" | "usb4" | "thunderbolt" | "hdmi21";

type DisplaySeed = {
  name: string;
  slug: string;
  technology: DisplayTechnologyKey;
  size: number;
  width: number;
  height: number;
  refresh: number;
  peakNits?: number;
  role?: string;
};

export type CatalogModuleSeed = {
  modelSlug: string;
  chipset: {
    name: string;
    slug: string;
    maker: string;
    cpuName: string;
    cpuSlug: string;
    cpuMaker?: string;
    cores: number;
    threads?: number;
    isa?: string;
    gpuName?: string;
    gpuSlug?: string;
    gpuMaker?: string;
    gpuRole?: string;
  };
  memory: {
    standard: MemoryKey;
    capacityGb: number;
    speedMhz?: number;
  };
  storage: {
    standard: StorageKey;
    capacityGb: number;
    expandable?: boolean;
    expansionMaxGb?: number;
  };
  display?: DisplaySeed;
  secondaryDisplay?: DisplaySeed;
  battery?: {
    capacityMah: number;
    energyWh?: number;
    wiredW?: number;
    wirelessW?: number;
    role?: string;
  };
  operatingSystem: OperatingSystemKey;
  wireless: WirelessKey[];
  ports: Array<{ standard: PortKey; count: number }>;
  camera?: { megapixel: number; aperture: number };
};

export const EXTENDED_CATALOG_MODULES: CatalogModuleSeed[] = [
  {
    modelSlug: "iphone-16",
    chipset: {
      name: "Apple A18",
      slug: "apple-a18",
      maker: "apple",
      cpuName: "Apple A18 CPU",
      cpuSlug: "apple-a18-cpu",
      cores: 6,
      gpuName: "Apple GPU (A18)",
      gpuSlug: "apple-gpu-a18",
    },
    memory: { standard: "lpddr5x", capacityGb: 8, speedMhz: 4266 },
    storage: { standard: "apple-nvme", capacityGb: 128 },
    display: {
      name: "iPhone 16 Super Retina XDR",
      slug: "iphone-16-display",
      technology: "oled",
      size: 6.1,
      width: 1179,
      height: 2556,
      refresh: 60,
      peakNits: 2000,
    },
    battery: { capacityMah: 3561, wiredW: 20, wirelessW: 25 },
    operatingSystem: "ios18",
    wireless: ["wifi7", "bluetooth53", "cellular5g"],
    ports: [{ standard: "usb-c-2", count: 1 }],
    camera: { megapixel: 48, aperture: 1.6 },
  },
  {
    modelSlug: "galaxy-z-fold6",
    chipset: {
      name: "Snapdragon 8 Gen 3",
      slug: "snapdragon-8-gen-3",
      maker: "qualcomm",
      cpuName: "Qualcomm Kryo 8 Gen 3 CPU",
      cpuSlug: "qualcomm-kryo-8-gen-3-cpu",
      cores: 8,
      gpuName: "Adreno 750",
      gpuSlug: "adreno-750",
    },
    memory: { standard: "lpddr5x", capacityGb: 12, speedMhz: 4266 },
    storage: { standard: "ufs4", capacityGb: 256 },
    display: {
      name: "Galaxy Z Fold6 Main Dynamic AMOLED 2X",
      slug: "galaxy-z-fold6-main-display",
      technology: "ltpo-oled",
      size: 7.6,
      width: 1856,
      height: 2160,
      refresh: 120,
      peakNits: 2600,
    },
    secondaryDisplay: {
      name: "Galaxy Z Fold6 Cover Display",
      slug: "galaxy-z-fold6-cover-display",
      technology: "amoled",
      size: 6.3,
      width: 968,
      height: 2376,
      refresh: 120,
      role: "cover",
    },
    battery: { capacityMah: 4400, wiredW: 25, wirelessW: 15 },
    operatingSystem: "android14",
    wireless: ["wifi6e", "bluetooth53", "cellular5g"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 50, aperture: 1.8 },
  },
  {
    modelSlug: "pixel-9a",
    chipset: {
      name: "Google Tensor G4",
      slug: "google-tensor-g4",
      maker: "google",
      cpuName: "Google Tensor G4 CPU",
      cpuSlug: "google-tensor-g4-cpu",
      cores: 8,
      gpuName: "Mali-G715 MP7",
      gpuSlug: "mali-g715-mp7",
      gpuMaker: "google",
    },
    memory: { standard: "lpddr5x", capacityGb: 8, speedMhz: 4266 },
    storage: { standard: "ufs31", capacityGb: 128 },
    display: {
      name: "Pixel 9a Actua Display",
      slug: "pixel-9a-display",
      technology: "oled",
      size: 6.3,
      width: 1080,
      height: 2424,
      refresh: 120,
      peakNits: 2700,
    },
    battery: { capacityMah: 5100, wiredW: 23, wirelessW: 7 },
    operatingSystem: "android15",
    wireless: ["wifi6e", "bluetooth53", "cellular5g"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 48, aperture: 1.7 },
  },
  {
    modelSlug: "xiaomi-15",
    chipset: {
      name: "Snapdragon 8 Elite",
      slug: "snapdragon-8-elite",
      maker: "qualcomm",
      cpuName: "Qualcomm Oryon CPU",
      cpuSlug: "qualcomm-oryon-8-elite-cpu",
      cores: 8,
      gpuName: "Adreno 830",
      gpuSlug: "adreno-830",
    },
    memory: { standard: "lpddr5x", capacityGb: 12, speedMhz: 4800 },
    storage: { standard: "ufs4", capacityGb: 256 },
    display: {
      name: "Xiaomi 15 CrystalRes AMOLED",
      slug: "xiaomi-15-display",
      technology: "ltpo-oled",
      size: 6.36,
      width: 1200,
      height: 2670,
      refresh: 120,
      peakNits: 3200,
    },
    battery: { capacityMah: 5240, wiredW: 90, wirelessW: 50 },
    operatingSystem: "android15",
    wireless: ["wifi7", "bluetooth54", "cellular5g"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 50, aperture: 1.6 },
  },
  {
    modelSlug: "sony-xperia-1-vi",
    chipset: {
      name: "Snapdragon 8 Gen 3",
      slug: "snapdragon-8-gen-3",
      maker: "qualcomm",
      cpuName: "Qualcomm Kryo 8 Gen 3 CPU",
      cpuSlug: "qualcomm-kryo-8-gen-3-cpu",
      cores: 8,
      gpuName: "Adreno 750",
      gpuSlug: "adreno-750",
    },
    memory: { standard: "lpddr5x", capacityGb: 12, speedMhz: 4266 },
    storage: {
      standard: "ufs4",
      capacityGb: 256,
      expandable: true,
      expansionMaxGb: 1500,
    },
    display: {
      name: "Xperia 1 VI BRAVIA OLED",
      slug: "xperia-1-vi-display",
      technology: "ltpo-oled",
      size: 6.5,
      width: 1080,
      height: 2340,
      refresh: 120,
      peakNits: 1300,
    },
    battery: { capacityMah: 5000, wiredW: 30, wirelessW: 15 },
    operatingSystem: "android14",
    wireless: ["wifi7", "bluetooth54", "cellular5g"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 48, aperture: 1.9 },
  },
  {
    modelSlug: "oneplus-13",
    chipset: {
      name: "Snapdragon 8 Elite",
      slug: "snapdragon-8-elite",
      maker: "qualcomm",
      cpuName: "Qualcomm Oryon CPU",
      cpuSlug: "qualcomm-oryon-8-elite-cpu",
      cores: 8,
      gpuName: "Adreno 830",
      gpuSlug: "adreno-830",
    },
    memory: { standard: "lpddr5x", capacityGb: 12, speedMhz: 4800 },
    storage: { standard: "ufs4", capacityGb: 256 },
    display: {
      name: "OnePlus 13 ProXDR LTPO",
      slug: "oneplus-13-display",
      technology: "ltpo-oled",
      size: 6.82,
      width: 1440,
      height: 3168,
      refresh: 120,
      peakNits: 4500,
    },
    battery: { capacityMah: 6000, wiredW: 100, wirelessW: 50 },
    operatingSystem: "android15",
    wireless: ["wifi7", "bluetooth54", "cellular5g"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 50, aperture: 1.6 },
  },
  {
    modelSlug: "oppo-find-x8-pro",
    chipset: {
      name: "MediaTek Dimensity 9400",
      slug: "mediatek-dimensity-9400",
      maker: "mediatek",
      cpuName: "Dimensity 9400 CPU",
      cpuSlug: "dimensity-9400-cpu",
      cores: 8,
      gpuName: "Immortalis-G925 MC12",
      gpuSlug: "immortalis-g925-mc12",
      gpuMaker: "mediatek",
    },
    memory: { standard: "lpddr5x", capacityGb: 16, speedMhz: 4800 },
    storage: { standard: "ufs4", capacityGb: 512 },
    display: {
      name: "Find X8 Pro LTPO AMOLED",
      slug: "oppo-find-x8-pro-display",
      technology: "ltpo-oled",
      size: 6.78,
      width: 1264,
      height: 2780,
      refresh: 120,
      peakNits: 4500,
    },
    battery: { capacityMah: 5910, wiredW: 80, wirelessW: 50 },
    operatingSystem: "android15",
    wireless: ["wifi7", "bluetooth54", "cellular5g"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 50, aperture: 1.6 },
  },
  {
    modelSlug: "vivo-x200-pro",
    chipset: {
      name: "MediaTek Dimensity 9400",
      slug: "mediatek-dimensity-9400",
      maker: "mediatek",
      cpuName: "Dimensity 9400 CPU",
      cpuSlug: "dimensity-9400-cpu",
      cores: 8,
      gpuName: "Immortalis-G925 MC12",
      gpuSlug: "immortalis-g925-mc12",
      gpuMaker: "mediatek",
    },
    memory: { standard: "lpddr5x", capacityGb: 16, speedMhz: 4800 },
    storage: { standard: "ufs4", capacityGb: 512 },
    display: {
      name: "vivo X200 Pro LTPO AMOLED",
      slug: "vivo-x200-pro-display",
      technology: "ltpo-oled",
      size: 6.78,
      width: 1260,
      height: 2800,
      refresh: 120,
      peakNits: 4500,
    },
    battery: { capacityMah: 6000, wiredW: 90, wirelessW: 30 },
    operatingSystem: "android15",
    wireless: ["wifi7", "bluetooth54", "cellular5g"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 50, aperture: 1.6 },
  },
  {
    modelSlug: "nothing-phone-2",
    chipset: {
      name: "Snapdragon 8+ Gen 1",
      slug: "snapdragon-8-plus-gen-1",
      maker: "qualcomm",
      cpuName: "Qualcomm Kryo 8+ Gen 1 CPU",
      cpuSlug: "qualcomm-kryo-8-plus-gen-1-cpu",
      cores: 8,
      gpuName: "Adreno 730",
      gpuSlug: "adreno-730",
    },
    memory: { standard: "lpddr5", capacityGb: 12, speedMhz: 3200 },
    storage: { standard: "ufs31", capacityGb: 256 },
    display: {
      name: "Nothing Phone (2) LTPO OLED",
      slug: "nothing-phone-2-display",
      technology: "ltpo-oled",
      size: 6.7,
      width: 1080,
      height: 2412,
      refresh: 120,
      peakNits: 1600,
    },
    battery: { capacityMah: 4700, wiredW: 45, wirelessW: 15 },
    operatingSystem: "android13",
    wireless: ["wifi6e", "bluetooth53", "cellular5g"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 50, aperture: 1.9 },
  },
  {
    modelSlug: "huawei-pura-70-ultra",
    chipset: {
      name: "Kirin 9010",
      slug: "kirin-9010",
      maker: "huawei",
      cpuName: "Kirin 9010 CPU",
      cpuSlug: "kirin-9010-cpu",
      cores: 8,
      threads: 12,
      gpuName: "Maleoon 910",
      gpuSlug: "maleoon-910",
      gpuMaker: "huawei",
    },
    memory: { standard: "lpddr5x", capacityGb: 16, speedMhz: 4266 },
    storage: { standard: "ufs4", capacityGb: 512 },
    display: {
      name: "Pura 70 Ultra LTPO OLED",
      slug: "huawei-pura-70-ultra-display",
      technology: "ltpo-oled",
      size: 6.8,
      width: 1260,
      height: 2844,
      refresh: 120,
      peakNits: 2500,
    },
    battery: { capacityMah: 5050, wiredW: 100, wirelessW: 80 },
    operatingSystem: "harmonyOs42",
    wireless: ["wifi6e", "bluetooth53", "cellular5g"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 50, aperture: 1.6 },
  },
  {
    modelSlug: "galaxy-tab-s10-ultra",
    chipset: {
      name: "MediaTek Dimensity 9300+",
      slug: "mediatek-dimensity-9300-plus",
      maker: "mediatek",
      cpuName: "Dimensity 9300+ CPU",
      cpuSlug: "dimensity-9300-plus-cpu",
      cores: 8,
      gpuName: "Immortalis-G720 MC12",
      gpuSlug: "immortalis-g720-mc12",
      gpuMaker: "mediatek",
    },
    memory: { standard: "lpddr5x", capacityGb: 12, speedMhz: 4800 },
    storage: {
      standard: "ufs4",
      capacityGb: 256,
      expandable: true,
      expansionMaxGb: 1500,
    },
    display: {
      name: "Galaxy Tab S10 Ultra Dynamic AMOLED 2X",
      slug: "galaxy-tab-s10-ultra-display",
      technology: "amoled",
      size: 14.6,
      width: 1848,
      height: 2960,
      refresh: 120,
      peakNits: 930,
    },
    battery: { capacityMah: 11200, wiredW: 45 },
    operatingSystem: "android14",
    wireless: ["wifi7", "bluetooth53"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 13, aperture: 2.0 },
  },
  {
    modelSlug: "ipad-mini-a17-pro",
    chipset: {
      name: "Apple A17 Pro",
      slug: "apple-a17-pro",
      maker: "apple",
      cpuName: "Apple A17 Pro CPU",
      cpuSlug: "apple-a17-pro-cpu",
      cores: 6,
      gpuName: "Apple GPU (A17 Pro)",
      gpuSlug: "apple-gpu-a17-pro",
    },
    memory: { standard: "lpddr5", capacityGb: 8, speedMhz: 3200 },
    storage: { standard: "apple-nvme", capacityGb: 128 },
    display: {
      name: "iPad mini Liquid Retina",
      slug: "ipad-mini-a17-pro-display",
      technology: "ips-lcd",
      size: 8.3,
      width: 1488,
      height: 2266,
      refresh: 60,
      peakNits: 500,
    },
    battery: { capacityMah: 5078, energyWh: 19.3, wiredW: 20 },
    operatingSystem: "ipadOs18",
    wireless: ["wifi6e", "bluetooth53"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 12, aperture: 1.8 },
  },
  {
    modelSlug: "oneplus-pad-2",
    chipset: {
      name: "Snapdragon 8 Gen 3",
      slug: "snapdragon-8-gen-3",
      maker: "qualcomm",
      cpuName: "Qualcomm Kryo 8 Gen 3 CPU",
      cpuSlug: "qualcomm-kryo-8-gen-3-cpu",
      cores: 8,
      gpuName: "Adreno 750",
      gpuSlug: "adreno-750",
    },
    memory: { standard: "lpddr5x", capacityGb: 12, speedMhz: 4266 },
    storage: { standard: "ufs31", capacityGb: 256 },
    display: {
      name: "OnePlus Pad 2 3K Display",
      slug: "oneplus-pad-2-display",
      technology: "ips-lcd",
      size: 12.1,
      width: 2120,
      height: 3000,
      refresh: 144,
      peakNits: 900,
    },
    battery: { capacityMah: 9510, wiredW: 67 },
    operatingSystem: "android14",
    wireless: ["wifi7", "bluetooth54"],
    ports: [{ standard: "usb-c", count: 1 }],
    camera: { megapixel: 13, aperture: 2.2 },
  },
  {
    modelSlug: "surface-pro-11",
    chipset: {
      name: "Snapdragon X Plus X1P-64-100",
      slug: "snapdragon-x-plus-x1p-64-100",
      maker: "qualcomm",
      cpuName: "Qualcomm Oryon X Plus CPU",
      cpuSlug: "qualcomm-oryon-x-plus-cpu",
      cores: 10,
      gpuName: "Adreno X1-85",
      gpuSlug: "adreno-x1-85",
    },
    memory: { standard: "lpddr5x", capacityGb: 16, speedMhz: 4224 },
    storage: { standard: "nvme", capacityGb: 256 },
    display: {
      name: "Surface Pro 11 PixelSense Flow",
      slug: "surface-pro-11-display",
      technology: "ips-lcd",
      size: 13,
      width: 1920,
      height: 2880,
      refresh: 120,
      peakNits: 600,
    },
    battery: { capacityMah: 4800, energyWh: 48, wiredW: 65 },
    operatingSystem: "windows11",
    wireless: ["wifi7", "bluetooth54"],
    ports: [{ standard: "usb4", count: 2 }],
    camera: { megapixel: 10, aperture: 2.0 },
  },
  {
    modelSlug: "macbook-air-13-m4",
    chipset: {
      name: "Apple M4",
      slug: "apple-m4",
      maker: "apple",
      cpuName: "Apple M4 CPU",
      cpuSlug: "apple-m4-cpu",
      cores: 10,
      gpuName: "Apple GPU (M4)",
      gpuSlug: "apple-gpu-m4",
    },
    memory: { standard: "unified", capacityGb: 16, speedMhz: 4266 },
    storage: { standard: "apple-nvme", capacityGb: 256 },
    display: {
      name: "MacBook Air 13.6 Liquid Retina",
      slug: "macbook-air-13-m4-display",
      technology: "ips-lcd",
      size: 13.6,
      width: 1664,
      height: 2560,
      refresh: 60,
      peakNits: 500,
    },
    battery: { capacityMah: 4382, energyWh: 53.8, wiredW: 70 },
    operatingSystem: "macOs15",
    wireless: ["wifi6e", "bluetooth53"],
    ports: [{ standard: "thunderbolt", count: 2 }],
    camera: { megapixel: 12, aperture: 2.0 },
  },
  {
    modelSlug: "dell-xps-13-9345",
    chipset: {
      name: "Snapdragon X Elite X1E-80-100",
      slug: "snapdragon-x-elite-x1e-80-100",
      maker: "qualcomm",
      cpuName: "Qualcomm Oryon X Elite CPU",
      cpuSlug: "qualcomm-oryon-x-elite-cpu",
      cores: 12,
      gpuName: "Adreno X1-85",
      gpuSlug: "adreno-x1-85",
    },
    memory: { standard: "lpddr5x", capacityGb: 16, speedMhz: 4224 },
    storage: { standard: "nvme", capacityGb: 512 },
    display: {
      name: "Dell XPS 13 InfinityEdge",
      slug: "dell-xps-13-9345-display",
      technology: "ips-lcd",
      size: 13.4,
      width: 1200,
      height: 1920,
      refresh: 120,
      peakNits: 500,
    },
    battery: { capacityMah: 7200, energyWh: 55, wiredW: 60 },
    operatingSystem: "windows11",
    wireless: ["wifi7", "bluetooth54"],
    ports: [{ standard: "usb4", count: 2 }],
    camera: { megapixel: 2, aperture: 2.0 },
  },
  {
    modelSlug: "asus-rog-zephyrus-g14-2024",
    chipset: {
      name: "AMD Ryzen 9 8945HS",
      slug: "amd-ryzen-9-8945hs",
      maker: "amd",
      cpuName: "AMD Ryzen 9 8945HS CPU",
      cpuSlug: "amd-ryzen-9-8945hs-cpu",
      cores: 8,
      threads: 16,
      isa: "x86-64",
      gpuName: "NVIDIA GeForce RTX 4060 Laptop GPU",
      gpuSlug: "nvidia-geforce-rtx-4060-laptop",
      gpuMaker: "nvidia",
      gpuRole: "discrete",
    },
    memory: { standard: "ddr5", capacityGb: 16, speedMhz: 6400 },
    storage: { standard: "nvme", capacityGb: 1024 },
    display: {
      name: "ROG Nebula OLED 14-inch",
      slug: "rog-zephyrus-g14-2024-display",
      technology: "oled",
      size: 14,
      width: 1800,
      height: 2880,
      refresh: 120,
      peakNits: 500,
    },
    battery: { capacityMah: 4750, energyWh: 73, wiredW: 180 },
    operatingSystem: "windows11",
    wireless: ["wifi6e", "bluetooth53"],
    ports: [
      { standard: "usb4", count: 1 },
      { standard: "hdmi21", count: 1 },
    ],
    camera: { megapixel: 2, aperture: 2.0 },
  },
  {
    modelSlug: "thinkpad-x1-carbon-gen-13",
    chipset: {
      name: "Intel Core Ultra 7 258V",
      slug: "intel-core-ultra-7-258v",
      maker: "intel",
      cpuName: "Intel Core Ultra 7 258V CPU",
      cpuSlug: "intel-core-ultra-7-258v-cpu",
      cores: 8,
      threads: 8,
      isa: "x86-64",
      gpuName: "Intel Arc 140V",
      gpuSlug: "intel-arc-140v",
      gpuMaker: "intel",
    },
    memory: { standard: "ddr5", capacityGb: 32, speedMhz: 8533 },
    storage: { standard: "nvme", capacityGb: 1024 },
    display: {
      name: "ThinkPad X1 Carbon 14-inch OLED",
      slug: "thinkpad-x1-carbon-gen-13-display",
      technology: "oled",
      size: 14,
      width: 1800,
      height: 2880,
      refresh: 120,
      peakNits: 500,
    },
    battery: { capacityMah: 5040, energyWh: 57, wiredW: 65 },
    operatingSystem: "windows11",
    wireless: ["wifi7", "bluetooth54"],
    ports: [
      { standard: "thunderbolt", count: 2 },
      { standard: "hdmi21", count: 1 },
    ],
    camera: { megapixel: 8, aperture: 2.0 },
  },
  {
    modelSlug: "surface-laptop-7-13",
    chipset: {
      name: "Snapdragon X Elite X1E-80-100",
      slug: "snapdragon-x-elite-x1e-80-100",
      maker: "qualcomm",
      cpuName: "Qualcomm Oryon X Elite CPU",
      cpuSlug: "qualcomm-oryon-x-elite-cpu",
      cores: 12,
      gpuName: "Adreno X1-85",
      gpuSlug: "adreno-x1-85",
    },
    memory: { standard: "lpddr5x", capacityGb: 16, speedMhz: 4224 },
    storage: { standard: "nvme", capacityGb: 512 },
    display: {
      name: "Surface Laptop 7 PixelSense Flow",
      slug: "surface-laptop-7-display",
      technology: "ips-lcd",
      size: 13.8,
      width: 1536,
      height: 2304,
      refresh: 120,
      peakNits: 600,
    },
    battery: { capacityMah: 7200, energyWh: 54, wiredW: 65 },
    operatingSystem: "windows11",
    wireless: ["wifi7", "bluetooth54"],
    ports: [
      { standard: "usb4", count: 2 },
      { standard: "usb-c", count: 1 },
    ],
    camera: { megapixel: 2, aperture: 2.0 },
  },
  {
    modelSlug: "apple-watch-series-10-46mm",
    chipset: {
      name: "Apple S10 SiP",
      slug: "apple-s10-sip",
      maker: "apple",
      cpuName: "Apple S10 CPU",
      cpuSlug: "apple-s10-cpu",
      cores: 2,
      gpuName: "Apple S10 GPU",
      gpuSlug: "apple-s10-gpu",
    },
    memory: { standard: "lpddr4x", capacityGb: 2, speedMhz: 1600 },
    storage: { standard: "emmc", capacityGb: 64 },
    display: {
      name: "Apple Watch Series 10 LTPO3 OLED",
      slug: "apple-watch-series-10-display",
      technology: "ltpo-oled",
      size: 1.96,
      width: 416,
      height: 496,
      refresh: 60,
      peakNits: 2000,
    },
    battery: { capacityMah: 327, wiredW: 5, wirelessW: 5 },
    operatingSystem: "watchOs11",
    wireless: ["wifi5", "bluetooth53"],
    ports: [],
  },
  {
    modelSlug: "garmin-fenix-8-amoled-47mm",
    chipset: {
      name: "Garmin fēnix 8 Platform",
      slug: "garmin-fenix-8-platform",
      maker: "garmin",
      cpuName: "Garmin fēnix 8 Controller",
      cpuSlug: "garmin-fenix-8-controller",
      cores: 2,
    },
    memory: { standard: "embedded", capacityGb: 1, speedMhz: 800 },
    storage: { standard: "emmc", capacityGb: 32 },
    display: {
      name: "Garmin fēnix 8 AMOLED",
      slug: "garmin-fenix-8-display",
      technology: "amoled",
      size: 1.4,
      width: 454,
      height: 454,
      refresh: 60,
      peakNits: 1000,
    },
    battery: { capacityMah: 470, wiredW: 5 },
    operatingSystem: "garminOs",
    wireless: ["wifi5", "bluetooth53"],
    ports: [],
  },
  {
    modelSlug: "pixel-watch-3-45mm",
    chipset: {
      name: "Qualcomm SW5100",
      slug: "qualcomm-sw5100",
      maker: "qualcomm",
      cpuName: "Qualcomm SW5100 CPU",
      cpuSlug: "qualcomm-sw5100-cpu",
      cores: 4,
      gpuName: "Adreno A702",
      gpuSlug: "adreno-a702",
    },
    memory: { standard: "lpddr4x", capacityGb: 2, speedMhz: 2133 },
    storage: { standard: "emmc", capacityGb: 32 },
    display: {
      name: "Pixel Watch 3 Actua Display",
      slug: "pixel-watch-3-45-display",
      technology: "ltpo-oled",
      size: 1.45,
      width: 456,
      height: 456,
      refresh: 60,
      peakNits: 2000,
    },
    battery: { capacityMah: 420, wiredW: 5 },
    operatingSystem: "wearOs5",
    wireless: ["wifi5", "bluetooth53"],
    ports: [],
  },
  {
    modelSlug: "galaxy-buds3-pro",
    chipset: {
      name: "Samsung Galaxy Buds3 Pro SiP",
      slug: "samsung-buds3-pro-sip",
      maker: "samsung",
      cpuName: "Samsung Buds3 Pro Audio Controller",
      cpuSlug: "samsung-buds3-pro-audio-controller",
      cores: 2,
    },
    memory: { standard: "embedded", capacityGb: 1 },
    storage: { standard: "emmc", capacityGb: 1 },
    battery: { capacityMah: 515, wiredW: 5, wirelessW: 5, role: "case" },
    operatingSystem: "samsungEarbuds",
    wireless: ["bluetooth54"],
    ports: [{ standard: "usb-c-2", count: 1 }],
  },
  {
    modelSlug: "sony-wf-1000xm5",
    chipset: {
      name: "Sony Integrated Processor V2",
      slug: "sony-integrated-processor-v2",
      maker: "sony",
      cpuName: "Sony V2 Audio Controller",
      cpuSlug: "sony-v2-audio-controller",
      cores: 2,
    },
    memory: { standard: "embedded", capacityGb: 1 },
    storage: { standard: "emmc", capacityGb: 1 },
    battery: { capacityMah: 500, wiredW: 5, wirelessW: 5, role: "case" },
    operatingSystem: "sonyEarbuds",
    wireless: ["bluetooth53"],
    ports: [{ standard: "usb-c-2", count: 1 }],
  },
  {
    modelSlug: "bose-quietcomfort-ultra-earbuds",
    chipset: {
      name: "Qualcomm S5 Audio SoC",
      slug: "qualcomm-s5-audio-soc",
      maker: "qualcomm",
      cpuName: "Qualcomm S5 Audio Controller",
      cpuSlug: "qualcomm-s5-audio-controller",
      cores: 2,
    },
    memory: { standard: "embedded", capacityGb: 1 },
    storage: { standard: "emmc", capacityGb: 1 },
    battery: { capacityMah: 750, wiredW: 5, role: "case" },
    operatingSystem: "boseEarbuds",
    wireless: ["bluetooth53"],
    ports: [{ standard: "usb-c-2", count: 1 }],
  },
  {
    modelSlug: "lg-oled-evo-g4-65",
    chipset: {
      name: "LG α11 AI Processor 4K",
      slug: "lg-alpha-11-ai-processor",
      maker: "lg",
      cpuName: "LG α11 CPU",
      cpuSlug: "lg-alpha-11-cpu",
      cores: 4,
      gpuName: "LG α11 Graphics",
      gpuSlug: "lg-alpha-11-graphics",
      gpuMaker: "lg",
    },
    memory: { standard: "lpddr4x", capacityGb: 4, speedMhz: 2133 },
    storage: { standard: "emmc", capacityGb: 32 },
    display: {
      name: "LG OLED evo G4 65-inch Panel",
      slug: "lg-oled-evo-g4-65-display",
      technology: "oled",
      size: 64.5,
      width: 3840,
      height: 2160,
      refresh: 144,
      peakNits: 1500,
    },
    operatingSystem: "webOs24",
    wireless: ["wifi6e", "bluetooth53"],
    ports: [{ standard: "hdmi21", count: 4 }],
  },
  {
    modelSlug: "sony-bravia-9-65",
    chipset: {
      name: "Sony XR Processor",
      slug: "sony-xr-processor-2024",
      maker: "sony",
      cpuName: "Sony XR CPU",
      cpuSlug: "sony-xr-cpu-2024",
      cores: 4,
      gpuName: "Sony XR Graphics",
      gpuSlug: "sony-xr-graphics-2024",
      gpuMaker: "sony",
    },
    memory: { standard: "lpddr4x", capacityGb: 4, speedMhz: 2133 },
    storage: { standard: "emmc", capacityGb: 32 },
    display: {
      name: "Sony BRAVIA 9 Mini LED 65-inch Panel",
      slug: "sony-bravia-9-65-display",
      technology: "mini-led",
      size: 64.5,
      width: 3840,
      height: 2160,
      refresh: 120,
      peakNits: 3000,
    },
    operatingSystem: "googleTv",
    wireless: ["wifi6e", "bluetooth53"],
    ports: [{ standard: "hdmi21", count: 4 }],
  },
  {
    modelSlug: "nintendo-switch-oled",
    chipset: {
      name: "NVIDIA Tegra X1",
      slug: "nvidia-tegra-x1-switch",
      maker: "nvidia",
      cpuName: "Tegra X1 ARM CPU",
      cpuSlug: "tegra-x1-arm-cpu",
      cpuMaker: "nvidia",
      cores: 8,
      gpuName: "NVIDIA Maxwell GM20B",
      gpuSlug: "nvidia-maxwell-gm20b",
      gpuMaker: "nvidia",
    },
    memory: { standard: "lpddr4x", capacityGb: 4, speedMhz: 1600 },
    storage: {
      standard: "emmc",
      capacityGb: 64,
      expandable: true,
      expansionMaxGb: 2048,
    },
    display: {
      name: "Nintendo Switch OLED Display",
      slug: "nintendo-switch-oled-display",
      technology: "oled",
      size: 7,
      width: 1280,
      height: 720,
      refresh: 60,
      peakNits: 350,
    },
    battery: { capacityMah: 4310, energyWh: 16, wiredW: 39 },
    operatingSystem: "switchOs",
    wireless: ["wifi5", "bluetooth50"],
    ports: [{ standard: "usb-c", count: 1 }],
  },
  {
    modelSlug: "steam-deck-oled",
    chipset: {
      name: "AMD Sephiroth APU",
      slug: "amd-sephiroth-apu",
      maker: "amd",
      cpuName: "AMD Zen 2 Steam Deck CPU",
      cpuSlug: "amd-zen2-steam-deck-cpu",
      cores: 4,
      threads: 8,
      isa: "x86-64",
      gpuName: "AMD RDNA 2 8CU",
      gpuSlug: "amd-rdna2-8cu",
      gpuMaker: "amd",
    },
    memory: { standard: "lpddr5", capacityGb: 16, speedMhz: 3200 },
    storage: {
      standard: "nvme",
      capacityGb: 1024,
      expandable: true,
      expansionMaxGb: 2048,
    },
    display: {
      name: "Steam Deck OLED HDR Display",
      slug: "steam-deck-oled-display",
      technology: "oled",
      size: 7.4,
      width: 1280,
      height: 800,
      refresh: 90,
      peakNits: 1000,
    },
    battery: { capacityMah: 5313, energyWh: 50, wiredW: 45 },
    operatingSystem: "steamOs",
    wireless: ["wifi6e", "bluetooth53"],
    ports: [{ standard: "usb-c", count: 1 }],
  },
  {
    modelSlug: "kindle-paperwhite-12th-gen",
    chipset: {
      name: "MediaTek MT8113",
      slug: "mediatek-mt8113",
      maker: "mediatek",
      cpuName: "MediaTek MT8113 CPU",
      cpuSlug: "mediatek-mt8113-cpu",
      cores: 2,
      gpuName: "MediaTek MT8113 Display Engine",
      gpuSlug: "mediatek-mt8113-display-engine",
      gpuMaker: "mediatek",
    },
    memory: { standard: "embedded", capacityGb: 1, speedMhz: 800 },
    storage: { standard: "emmc", capacityGb: 16 },
    display: {
      name: "Kindle Paperwhite 7-inch E Ink",
      slug: "kindle-paperwhite-12-display",
      technology: "e-ink",
      size: 7,
      width: 1264,
      height: 1680,
      refresh: 1,
      peakNits: 24,
    },
    battery: { capacityMah: 1900, wiredW: 10 },
    operatingSystem: "kindleOs",
    wireless: ["wifi5", "bluetooth50"],
    ports: [{ standard: "usb-c-2", count: 1 }],
  },
];
